; wEventFlags bit flags

	const_def
; The first eight flags are reset upon reloading the map
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_1
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_2
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_3
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_4
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_5
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_6
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_7
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_8
; used 8

; Kanto Gym Leader TM gifts
	const EVENT_GOT_TM34_BIDE
	const EVENT_GOT_TM11_BUBBLEBEAM
	const EVENT_GOT_TM42_SPARK
	const EVENT_GOT_TM21_GIGA_DRAIN
	const EVENT_GOT_TM06_TOXIC
	const EVENT_GOT_TM04_CALM_MIND
	const EVENT_GOT_TM38_FIRE_BLAST
	const EVENT_GOT_TM27_FISSURE
; used 8

; Johto Gym Leader TM gifts
	const EVENT_GOT_TM23_IRON_TAIL
	const EVENT_GOT_TM70_SHADOW_BALL
	const EVENT_GOT_TM73_ATTRACT
	const EVENT_GOT_TM81_X_SCISSOR
	const EVENT_GOT_TM43_SKY_ATTACK
	const EVENT_GOT_TM80_ANCIENTPOWER
	const_skip ;WHIRLPOOL PAGER, TM_WHIRLPOOL?
	const EVENT_GOT_TM72_DRAGONBREATH
; used 8

; HMs (pagers)
	const EVENT_GOT_HM01_CUT
	const EVENT_GOT_HM02_FLY
	const EVENT_GOT_HM03_SURF
	const EVENT_GOT_HM04_STRENGTH
	const EVENT_GOT_HM05_FLASH
	const EVENT_GOT_HM06_WHIRLPOOL
	const EVENT_GOT_HM07_WATERFALL
	const EVENT_GOT_TM58_ROCK_SMASH
;	const EVENT_GOT_TM56_HEADBUTT
; used 8

; Rods
	const EVENT_GOT_OLD_ROD
	const EVENT_GOT_GOOD_ROD
	const EVENT_GOT_SUPER_ROD
	const EVENT_GOT_JOHTO_LURE
	const EVENT_SUPER_ROD_LURE_ACTIVE
; used 5

; Gift TMs
	const EVENT_GOT_TM01_DYNAMICPUNCH
	const EVENT_GOT_TM10_HIDDEN_POWER
	const EVENT_GOT_TM13_ICE_BEAM
	const EVENT_GOT_TM18_COUNTER
	const EVENT_GOT_TM24_THUNDERBOLT
	const EVENT_GOT_TM29_PSYCHIC
	const EVENT_GOT_TM35_METRONOME
	const EVENT_GOT_TM36_SELFDESTRUCT
	const EVENT_GOT_TM39_SWIFT
	const EVENT_GOT_TM41_FLAMETHROWER
	const EVENT_GOT_TM56_HEADBUTT ; ilex forest, sooner?
	const EVENT_GOT_TM64_SWAGGER
	const EVENT_GOT_TM67_STEEL_WING
	const EVENT_GOT_TM69_CURSE
	const EVENT_GOT_TM76_SUNNY_DAY
	const EVENT_GOT_TM77_RAIN_DANCE
	const EVENT_GOT_TM78_SANDSTORM
	const_skip ; unused
; used 21

; Got stuff Kanto
	const EVENT_GOT_PEWTER_BOOST_ITEM
	const EVENT_GOT_MYSTIC_WATER
	const EVENT_GOT_BICYCLE
	const EVENT_GOT_ITEMFINDER
	const EVENT_GOT_EEVEE_FROM_CELADON_MANSION
	const EVENT_GOT_COIN_CASE
	const EVENT_GOT_COINS_FROM_CELADON_FISHING_GURU
	const EVENT_GOT_COINS_FROM_CELADON_FISHER
	const EVENT_GOT_COINS_FROM_CELADON_GENTLEMAN
	const EVENT_GOT_POKEFLUTE
	const EVENT_GOT_METAL_POWDER_FROM_COPYCAT
	const EVENT_GOT_POKEMON_FROM_DOJO
	const EVENT_GOT_HITMONLEE_FROM_DOJO
	const EVENT_GOT_HITMONCHAN_FROM_DOJO
	const EVENT_GOT_LAPRAS_FROM_SILPH_CO
	const EVENT_GOT_EXP_SHARE
	const EVENT_GOT_MASTER_BALL_FROM_SILPH_CO
	const EVENT_GOT_BERSERK_GENE
; Got stuff Johto
	const EVENT_GOT_SMOKE_BALL_FROM_CAPTAIN_ON_SS_AQUA
	const EVENT_GOT_DANCE_THEATER_LUCKY_EGG
	const EVENT_GOT_TYROGUE_FROM_KIYO
	const EVENT_GOT_QUICK_CLAW ;national park
	const EVENT_GOT_SQUIRTBOTTLE
	const EVENT_GOT_KINGS_ROCK_IN_SLOWPOKE_WELL
;	const EVENT_GOT_RAINBOW_WING
	const EVENT_GOT_NUGGET_FROM_RADIO_TOWER
	const EVENT_GOT_BRIGHTPOWDER_FROM_MARY
	const EVENT_GOT_BLACKGLASSES_IN_DARK_CAVE
;	const EVENT_GOT_CLEAR_BELL ;unused
;	const EVENT_GOT_SILVER_WING ;unused
	const EVENT_GOT_DRATINI ;from dragon shrine
	const EVENT_GOT_DRAGON_FANG
;	const EVENT_GOT_MASTER_BALL_FROM_ELM ;unused
; used 25
; group total used 83
; running total 83

	const_next 100
; Story events (silvermirror)
	const EVENT_INITIALIZED_EVENTS
	const EVENT_LISTENED_TO_INITIAL_RADIO
	const EVENT_FIRST_TIME_BANKING_WITH_MOM
	const EVENT_TALKED_TO_MOM_AFTER_GETTING_POKEDEX
	const EVENT_GOT_A_POKEMON_FROM_OAK
	const EVENT_GOT_CHARMANDER_FROM_OAK
	const EVENT_GOT_SQUIRTLE_FROM_OAK
	const EVENT_GOT_BULBASAUR_FROM_OAK
	const EVENT_ROUTE_1_GOT_POTION_SAMPLE
	const EVENT_COFFEE_GRAMPS_STOPPED_YOU
	const EVENT_GOT_OAKS_PARCEL
	const EVENT_GOT_POKEDEX ;oaks lab pokedex visibility
	const EVENT_GOT_POKEBALLS_FROM_OAK
	const EVENT_GOT_MAP_CARD
	const EVENT_BOUGHT_MAGIKARP
	const EVENT_MT_MOON_OBTAINED_FOSSIL ;mt moon fossils visibility
	const EVENT_HELPED_BILL
	const EVENT_GOT_ODD_EGG
	const EVENT_OAK_CALLED_ABOUT_SSANNE
	const EVENT_SS_ANNE_SET_SAIL
	const EVENT_VERMILION_GYM_SWITCH_2
	const EVENT_LISTENED_TO_FAN_CLUB_PRESIDENT
	const EVENT_OAK_CALLED_ABOUT_FLASH
	const EVENT_CELADON_MANSION_ROOF_GRAFFITI
	const EVENT_TALKED_TO_MAN_ABOUT_EEVEE
	const EVENT_OPENED_ROCKET_HIDEOUT
	const EVENT_GOT_ROCKET_HIDEOUT_LEFT_KEY
	const EVENT_OPENED_ROCKET_HIDEOUT_B1F_DOOR
	const EVENT_OPENED_ROCKET_HIDEOUT_B4F_DOOR
	const EVENT_FOUGHT_POKEMON_GHOST
	const EVENT_FOUGHT_SNORLAX
	const EVENT_WOKE_SNORLAX
	const EVENT_OAK_CALLED_ABOUT_SILPHCO
	const EVENT_GAVE_SAFFRON_GUARD_DRINK
	const EVENT_SILPH_CO_2F_DOOR_1
	const EVENT_SILPH_CO_2F_DOOR_2
	const EVENT_SILPH_CO_3F_DOOR_1
	const EVENT_SILPH_CO_3F_DOOR_2
	const EVENT_SILPH_CO_4F_DOOR_1
	const EVENT_SILPH_CO_4F_DOOR_2
	const EVENT_SILPH_CO_5F_DOOR_1
	const EVENT_SILPH_CO_5F_DOOR_2
	const EVENT_SILPH_CO_5F_DOOR_3
	const EVENT_SILPH_CO_6F_DOOR_1
	const EVENT_SILPH_CO_7F_DOOR_1
	const EVENT_SILPH_CO_7F_DOOR_2
	const EVENT_SILPH_CO_7F_DOOR_3
	const EVENT_SILPH_CO_8F_DOOR_1
	const EVENT_SILPH_CO_9F_DOOR_1
	const EVENT_SILPH_CO_9F_DOOR_2
	const EVENT_SILPH_CO_9F_DOOR_3
	const EVENT_SILPH_CO_9F_DOOR_4
	const EVENT_SILPH_CO_10F_DOOR_1
	const EVENT_SILPH_CO_11F_DOOR_1
	const EVENT_MET_KURTS_SON
	const EVENT_SAFARI_ZONE_ENTRANCE_OFFICER_SAFARI_GAME_ACTIVE
	const EVENT_SAFARI_ZONE_ENTRANCE_OFFICER_SAFARI_GAME_NOT_ACTIVE
	const EVENT_SEAFOAM_1F_BOULDER_1
	const EVENT_SEAFOAM_1F_BOULDER_2
	const EVENT_SEAFOAM_B1F_BOULDER_1
	const EVENT_SEAFOAM_B1F_BOULDER_2
	const EVENT_SEAFOAM_B2F_BOULDER_1
	const EVENT_SEAFOAM_B2F_BOULDER_2
	const EVENT_SEAFOAM_B3F_BOULDER_1
	const EVENT_SEAFOAM_B3F_BOULDER_X1
	const EVENT_SEAFOAM_B3F_BOULDER_X2
	const EVENT_SEAFOAM_B4F_BOULDER_X1
	const EVENT_POKEMON_MANSION_SECRET_SWITCH
	const EVENT_CINNABAR_GYM_LEADER_RETURNED
	const EVENT_CINNABAR_GYM_QUIZ_1
	const EVENT_CINNABAR_GYM_QUIZ_2
	const EVENT_CINNABAR_GYM_QUIZ_3
	const EVENT_CINNABAR_GYM_QUIZ_4
	const EVENT_CINNABAR_GYM_QUIZ_5
	const EVENT_CINNABAR_GYM_QUIZ_6
	const EVENT_OAK_CALLED_ABOUT_VIRIDIAN_GYM
	const EVENT_PEWTER_MUSEUM_OBTAINED_OLD_AMBER
	const EVENT_FOSSIL_SCIENTIST_WORKING
	const EVENT_FOSSIL_SCIENTIST_WORKING_HELIX
	const EVENT_FOSSIL_SCIENTIST_WORKING_DOME
	const EVENT_FOSSIL_SCIENTIST_WORKING_AMBER
	const EVENT_VIRIDIAN_GYM_LEADER_RETURNED
	const EVENT_VICTORY_ROAD_1F_BOULDER
	const EVENT_VICTORY_ROAD_2F_BOULDER1
	const EVENT_VICTORY_ROAD_2F_BOULDER2
	const EVENT_VICTORY_ROAD_3F_BOULDER1
	const EVENT_VICTORY_ROAD_3F_BOULDER2
	const EVENT_VICTORY_ROAD_BOULDER_FELL_THROUGH
	const EVENT_VICTORY_ROAD_1F_GATE_OPEN
	const EVENT_VICTORY_ROAD_2F_GATE_1_OPEN
	const EVENT_VICTORY_ROAD_2F_GATE_2_OPEN
	const EVENT_VICTORY_ROAD_3F_GATE_OPEN
	const EVENT_LORELEIS_ROOM_ENTRANCE_CLOSED
	const EVENT_LORELEIS_ROOM_EXIT_OPEN
	const EVENT_BRUNOS_ROOM_ENTRANCE_CLOSED
	const EVENT_BRUNOS_ROOM_EXIT_OPEN
	const EVENT_AGATHAS_ROOM_ENTRANCE_CLOSED
	const EVENT_AGATHAS_ROOM_EXIT_OPEN
	const EVENT_LANCES_ROOM_ENTRANCE_CLOSED
	const EVENT_LANCES_ROOM_EXIT_OPEN
	const EVENT_BEAT_ELITE_FOUR
	const EVENT_ENABLE_DIPLOMA_PRINTING
	const EVENT_FOUGHT_ARTICUNO
	const EVENT_FOUGHT_ZAPDOS
	const EVENT_FOUGHT_MOLTRES
	const EVENT_FOUGHT_MEWTWO
	const EVENT_FOUGHT_MEW
	const EVENT_CAUGHT_MISSINGNO
; 108
; Johto / postgame
	const EVENT_GOT_SS_TICKET_FROM_OAK
	const EVENT_FAST_SHIP_DESTINATION_OLIVINE
	const EVENT_FAST_SHIP_HAS_ARRIVED
	const EVENT_FAST_SHIP_COMPLETED_FIRST_TRIP
	const EVENT_FOUND_GIRL_IN_BURNED_TOWER
	const EVENT_HOLE_IN_BURNED_TOWER
	const EVENT_RELEASED_THE_BEASTS
	const EVENT_ROUTE_42_BOULDERS_CLEARED
	const EVENT_HELIX_FOSSIL_AT_MT_MORTAR
	const EVENT_DOME_FOSSIL_AT_MT_MORTAR
	const EVENT_MT_MORTAR_OBTAINED_FOSSIL
	const EVENT_MET_FLORIA
	const EVENT_TALKED_TO_FLORIA_AT_FLOWER_SHOP
	const EVENT_FOUGHT_SUDOWOODO
	const EVENT_ROUTE_36_BATTLE
	const EVENT_ROUTE_36_OPEN
	const EVENT_MADE_WHITNEY_CRY
	const EVENT_USED_BASEMENT_KEY
	const EVENT_GOT_GS_BALL_FROM_BILL
	const EVENT_MET_KURT
	const EVENT_CAN_GIVE_GS_BALL_TO_KURT
	const EVENT_KURTS_SON_SAW_GS_BALL
	const EVENT_GAVE_GS_BALL_TO_KURT
	const EVENT_FOREST_IS_RESTLESS
	const EVENT_PUT_GS_BALL_IN_SHRINE
	const EVENT_TALKED_TO_RUINS_SCIENTIST_AFTER_FALLING
	const EVENT_ROUTE_30_SAW_HOOH
	const EVENT_TIN_TOWER_ENTRANCE_ACCESS_GRANTED
	const EVENT_WISE_TRIO_EXPLAINED_CLEAR_BELL
	const EVENT_KOJI_ALLOWS_YOU_PASSAGE_TO_TIN_TOWER
	const EVENT_MET_PROF_ELM
	const EVENT_OAK_CALLED_ABOUT_RADIO_TOWER
	const EVENT_CLEARED_RADIO_TOWER
	const EVENT_BOULDER_IN_ICE_PATH_1
	const EVENT_BOULDER_IN_ICE_PATH_2
	const EVENT_BOULDER_IN_ICE_PATH_3
	const EVENT_BOULDER_IN_ICE_PATH_4
	const EVENT_BOULDER_IN_ICE_PATH_1A
	const EVENT_BOULDER_IN_ICE_PATH_2A
	const EVENT_BOULDER_IN_ICE_PATH_3A
	const EVENT_BOULDER_IN_ICE_PATH_4A
	const EVENT_NINJA_SECURITY_1
	const EVENT_NINJA_SECURITY_2
	const EVENT_NINJA_SECURITY_3
	const EVENT_NINJA_SECURITY_4
	const EVENT_NINJA_SECURITY_5
	const EVENT_NINJA_SECURITY_6
	const EVENT_NINJA_SECURITY_7
	const EVENT_NINJA_SECURITY_8
	const EVENT_TEAM_ROCKET_BASE_B1F_SWITCH
	const EVENT_TEAM_ROCKET_BASE_B3F_SWITCH_1
	const EVENT_TEAM_ROCKET_BASE_B3F_SWITCH_2
	const EVENT_TEAM_ROCKET_BASE_B3F_BOTH_SWITCHES
	const EVENT_NINJA_CHALLENGE_IN_PROGRESS
	const EVENT_DEFEATED_GOLD_MAGIKARP
	const EVENT_TALKED_TO_CLAIR_AT_LAKE_OF_RAGE
	const EVENT_CLAIR_RETURNED_TO_GYM
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_1
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_2
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_3
	const EVENT_ANSWERED_DRAGON_MASTER_QUIZ_WRONG ;in dragon shrine
	const EVENT_CLEARED_DRAGONS_DEN
;
	const EVENT_OPENED_MT_SILVER
	const EVENT_BEAT_SILVER_MIRROR
;
; misc
	const EVENT_FOUGHT_HO_OH
	const EVENT_FOUGHT_LUGIA
	const EVENT_SHOWED_RAINBOW_WING_TO_MR_POKEMON
	const EVENT_SHOWED_SILVER_WING_TO_MR_POKEMON
	const EVENT_MET_BUENA
	const EVENT_GOT_RADIO_TOWER_CARD_KEY
	const EVENT_USED_RADIO_TOWER_CARD_KEY
	const EVENT_OAK_REMIND_ABOUT_WATERFALL
	const EVENT_GAVE_SHUCKLE_TO_MANIA
	const EVENT_WARPED_FROM_ROUTE_35_NATIONAL_PARK_GATE
	const EVENT_LEFT_MONS_WITH_CONTEST_OFFICER
	const EVENT_CONTEST_OFFICER_HAS_SUN_STONE
	const EVENT_CONTEST_OFFICER_HAS_DUSK_STONE
	const EVENT_CONTEST_OFFICER_HAS_EVERSTONE
	const EVENT_CONTEST_OFFICER_HAS_LUM_BERRY
	const EVENT_CONTEST_OFFICER_HAS_SITRUS_BERRY
;	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_BLOCKED_OFF
;	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_1
;	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_2
;	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_3
; will use?
	const EVENT_MET_MONICA_OF_MONDAY
	const EVENT_GOT_SHARP_BEAK_FROM_MONICA
	const EVENT_MET_TUSCANY_OF_TUESDAY
	const EVENT_GOT_SILK_SCARF_FROM_TUSCANY
	const EVENT_MET_WESLEY_OF_WEDNESDAY
	const EVENT_GOT_BLACKBELT_FROM_WESLEY
	const EVENT_MET_ARTHUR_OF_THURSDAY
	const EVENT_GOT_HARD_STONE_FROM_ARTHUR
	const EVENT_MET_FRIEDA_OF_FRIDAY
	const EVENT_GOT_POISON_BARB_FROM_FRIEDA
	const EVENT_MET_SANTOS_OF_SATURDAY
	const EVENT_GOT_SPELL_TAG_FROM_SANTOS
	const EVENT_MET_SUNNY_OF_SUNDAY
	const EVENT_GOT_MAGNET_FROM_SUNNY
;
	const EVENT_BATTLE_TOWER_OPEN_CIVILIANS

	const EVENT_FOUGHT_SUICUNE
	const EVENT_LAKE_OF_RAGE_EXPLAINED_WEIRD_MAGIKARP
	const EVENT_LAKE_OF_RAGE_ASKED_FOR_MAGIKARP
	const EVENT_LAKE_OF_RAGE_ELIXIR_ON_STANDBY
	const EVENT_MET_BILLS_GRANDPA
	const EVENT_SHOWED_LICKITUNG_TO_BILLS_GRANDPA
	const EVENT_SHOWED_ODDISH_TO_BILLS_GRANDPA
	const EVENT_SHOWED_STARYU_TO_BILLS_GRANDPA
	const EVENT_SHOWED_GROWLITHE_VULPIX_TO_BILLS_GRANDPA
	const EVENT_SHOWED_PICHU_TO_BILLS_GRANDPA
	const EVENT_GOT_EVERSTONE_FROM_BILLS_GRANDPA
	const EVENT_GOT_LEAF_STONE_FROM_BILLS_GRANDPA
	const EVENT_GOT_WATER_STONE_FROM_BILLS_GRANDPA
	const EVENT_GOT_FIRE_STONE_FROM_BILLS_GRANDPA
	const EVENT_GOT_THUNDERSTONE_FROM_BILLS_GRANDPA
;
	const EVENT_SWITCH_1
	const EVENT_SWITCH_2
	const EVENT_SWITCH_3
	const EVENT_EMERGENCY_SWITCH
	const EVENT_SWITCH_4
	const EVENT_SWITCH_5
	const EVENT_SWITCH_6
	const EVENT_SWITCH_7
	const EVENT_SWITCH_8
	const EVENT_SWITCH_9
	const EVENT_SWITCH_10
	const EVENT_SWITCH_11
	const EVENT_SWITCH_12
	const EVENT_SWITCH_13
	const EVENT_SWITCH_14
;
;	const EVENT_UNCOVERED_STAIRCASE_IN_MAHOGANY_MART
;	const EVENT_TURNED_OFF_SECURITY_CAMERAS
;	const EVENT_SECURITY_CAMERA_1
;	const EVENT_SECURITY_CAMERA_2
;	const EVENT_SECURITY_CAMERA_3
;	const EVENT_SECURITY_CAMERA_4
;	const EVENT_SECURITY_CAMERA_5
;	const EVENT_EXPLODING_TRAP_1
;	const EVENT_EXPLODING_TRAP_2
;	const EVENT_EXPLODING_TRAP_3
;	const EVENT_EXPLODING_TRAP_4
;	const EVENT_EXPLODING_TRAP_5
;	const EVENT_EXPLODING_TRAP_6
;	const EVENT_EXPLODING_TRAP_7
;	const EVENT_EXPLODING_TRAP_8
;	const EVENT_EXPLODING_TRAP_9
;	const EVENT_EXPLODING_TRAP_10
;	const EVENT_EXPLODING_TRAP_11
;	const EVENT_EXPLODING_TRAP_12
;	const EVENT_EXPLODING_TRAP_13
;	const EVENT_EXPLODING_TRAP_14
;	const EVENT_EXPLODING_TRAP_15
;	const EVENT_EXPLODING_TRAP_16
;	const EVENT_EXPLODING_TRAP_17
;	const EVENT_EXPLODING_TRAP_18
;	const EVENT_EXPLODING_TRAP_19
;	const EVENT_EXPLODING_TRAP_20
;	const EVENT_EXPLODING_TRAP_21
;	const EVENT_EXPLODING_TRAP_22
; still referenced but should be removed/replaced
	const EVENT_RESTORED_POWER_TO_KANTO
	const EVENT_SET_WHEN_FOUGHT_HO_OH

; group used 215
; running total 315

	const_next 400
; Kanto people
; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.
	const EVENT_PALLET_TOWN_OAK
	const EVENT_PLAYERS_HOUSE_MOM_1
	const EVENT_PLAYERS_HOUSE_MOM_2
	const EVENT_PLAYERS_HOUSE_1F_NEIGHBOR
	const EVENT_BLUES_HOUSE_NEIGHBOR
	const EVENT_OAKS_LAB_RIVAL
	const EVENT_OAKS_LAB_OAK
	const EVENT_BLUES_ROOM_BULBASAUR
	const EVENT_BLUES_ROOM_CHARMANDER
	const EVENT_BLUES_ROOM_SQUIRTLE
	const EVENT_VIRIDIAN_CITY_COFFEE_GRAMPS
	const EVENT_VIRIDIAN_CITY_CATCHING_GRAMPS
	const EVENT_ROUTE_22_RIVAL
	const EVENT_PEWTER_CITY_BLOCKING_GUY ; unused
	const EVENT_CERULEAN_CITY_RIVAL
	const EVENT_CERULEAN_CITY_ROCKET
	const EVENT_NUGGET_BRIDGE_ROCKET
	const EVENT_DAY_CARE_MAN_IN_DAY_CARE
	const EVENT_DAY_CARE_MAN_ON_ROUTE_5
	const EVENT_DAY_CARE_MON_1
	const EVENT_DAY_CARE_MON_2
	const EVENT_SSANNE_2F_RIVAL
	const EVENT_SSANNE_FIRST_VISIT_NPCS
	const EVENT_SSANNE_TRAINERS_1A
	const EVENT_SSANNE_TRAINERS_2A ;first trip NPCs
	const EVENT_SSANNE_TRAINERS_3A
	const EVENT_SSANNE_TRAINERS_4A
	const EVENT_SSANNE_TRAINERS_5A
	const EVENT_SSANNE_TRAINERS_1B
	const EVENT_SSANNE_TRAINERS_2B
	const EVENT_SSANNE_TRAINERS_3B
	const EVENT_SSANNE_TRAINERS_4B
	const EVENT_SSANNE_TRAINERS_5B ;first trip NPCs
	const EVENT_SSANNE_TRAINERS_1C
	const EVENT_SSANNE_TRAINERS_2C
	const EVENT_SSANNE_TRAINERS_3C
	const EVENT_SSANNE_TRAINERS_4C ;first trip NPCs
	const EVENT_SSANNE_TRAINERS_5C
	const EVENT_POKEMON_TOWER_2F_RIVAL
	const EVENT_MR_FUJIS_HOUSE_MR_FUJI
	const EVENT_POKEMON_TOWER_7F_MR_FUJI
	const EVENT_CELADON_CITY_ROCKETS
	const EVENT_ROUTE_12_SNORLAX
	const EVENT_ROUTE_16_SNORLAX
	const EVENT_ROUTE_11_SNORLAX_RESPAWN
	const EVENT_SAFFRON_CITY_ROCKET_GUARD
	const EVENT_SAFFRON_CITY_ROCKET_SLEEP
	const EVENT_SAFFRON_CITY_ROCKETS
	const EVENT_SAFFRON_CITY_CIVILIANS
	const EVENT_SILPH_CO_7F_RIVAL
	const EVENT_COPYCAT_1
	const EVENT_COPYCAT_2
	const EVENT_COPYCATS_HOUSE_2F_DOLL
	const EVENT_SAFFRON_CITY_KURTS_SON
	const EVENT_KURTS_SONS_HOUSE_1F_KURTS_SON
	const EVENT_KURTS_SON_APRICORN_BALL
	const EVENT_SAFARI_ZONE_AREA_1_NPC1
	const EVENT_SAFARI_ZONE_AREA_1_NPC2
	const EVENT_SAFARI_ZONE_AREA_1_NPC3
	const EVENT_SAFARI_ZONE_AREA_2_NPC1
	const EVENT_SAFARI_ZONE_AREA_2_NPC2
	const EVENT_SAFARI_ZONE_AREA_2_NPC3
	const EVENT_SAFARI_ZONE_AREA_3_NPC1
	const EVENT_SAFARI_ZONE_AREA_3_NPC2
	const EVENT_SAFARI_ZONE_AREA_3_NPC3
	const EVENT_SAFARI_ZONE_AREA_4_NPC1
	const EVENT_SAFARI_ZONE_AREA_4_NPC2
	const EVENT_ROUTE_19_BOY
	const EVENT_CINNABAR_LAB_HELIX_FOSSIL
	const EVENT_CINNABAR_LAB_DOME_FOSSIL
	const EVENT_CINNABAR_LAB_OLD_AMBER
	const EVENT_VICTORY_ROAD_GATE_BLACKBELT
	const EVENT_INDIGO_POKECENTER_GYM_GUIDE
;	const EVENT_INDIGO_POKECENTER_LANCE
	const EVENT_LANCES_ROOM_RIVAL
	const EVENT_LANCES_ROOM_OAK
	const EVENT_MT_MOON_SQUARE_ROCK
	const EVENT_MT_MOON_SQUARE_CLEFAIRY
	const EVENT_TELEPORT_GUY
	const EVENT_ARTICUNO_APPEAR
	const EVENT_ZAPDOS_APPEAR
	const EVENT_MOLTRES_APPEAR
	const EVENT_MEWTWO_APPEAR
; used 85
; running total 485
;
; Johto people
; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.
	const EVENT_VERMILION_PORT_TICKET_SAILOR
	const EVENT_OLIVINE_PORT_TICKET_SAILOR
	const EVENT_FAST_SHIP_1F_ROCKETS
	const EVENT_FAST_SHIP_B1F_ROCKETS
	const EVENT_FAST_SHIP_ENGINE_ROOM_ROCKETS
	const EVENT_FAST_SHIP_CAPTAINS_CABIN_ROCKETS
	const EVENT_FAST_SHIP_SAILORS
;	const EVENT_FAST_SHIP_PASSENGERS_FIRST_TRIP
;	const EVENT_FAST_SHIP_PASSENGERS_KANTOBOUND
;	const EVENT_FAST_SHIP_PASSENGERS_JOHTOBOUND
	const EVENT_FAST_SHIP_TRAINERS_1A
	const EVENT_FAST_SHIP_TRAINERS_2A
	const EVENT_FAST_SHIP_TRAINERS_3A
	const EVENT_FAST_SHIP_TRAINERS_1B
	const EVENT_FAST_SHIP_TRAINERS_2B
	const EVENT_FAST_SHIP_TRAINERS_3B
	const EVENT_FAST_SHIP_TRAINERS_4B
	const EVENT_FAST_SHIP_B1F_FIELD_TRIP
	const EVENT_FAST_SHIP_B1F_SAILOR_A
	const EVENT_FAST_SHIP_B1F_SAILOR_B
	const EVENT_CIANWOOD_GYM_TRAINERS
	const EVENT_BURNED_TOWER_LOST_GIRL
	const EVENT_GRAMPS_IN_BURNED_TOWER
	const EVENT_BURNED_TOWER_B1F_BEASTS_1
	const EVENT_BURNED_TOWER_B1F_BEASTS_2
	const EVENT_ECRUTEAK_CITY_GIRL
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_YOUNGSTER
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_ROUTE_36_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_36_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_BUG_CATCHING_CONTESTANT_1A
	const EVENT_BUG_CATCHING_CONTESTANT_2A
	const EVENT_BUG_CATCHING_CONTESTANT_3A
	const EVENT_BUG_CATCHING_CONTESTANT_4A
	const EVENT_BUG_CATCHING_CONTESTANT_5A
	const EVENT_BUG_CATCHING_CONTESTANT_6A
	const EVENT_BUG_CATCHING_CONTESTANT_7A
	const EVENT_BUG_CATCHING_CONTESTANT_8A
	const EVENT_BUG_CATCHING_CONTESTANT_9A
	const EVENT_BUG_CATCHING_CONTESTANT_10A
	const EVENT_BUG_CATCHING_CONTESTANT_1B
	const EVENT_BUG_CATCHING_CONTESTANT_2B
	const EVENT_BUG_CATCHING_CONTESTANT_3B
	const EVENT_BUG_CATCHING_CONTESTANT_4B
	const EVENT_BUG_CATCHING_CONTESTANT_5B
	const EVENT_BUG_CATCHING_CONTESTANT_6B
	const EVENT_BUG_CATCHING_CONTESTANT_7B
	const EVENT_BUG_CATCHING_CONTESTANT_8B
	const EVENT_BUG_CATCHING_CONTESTANT_9B
	const EVENT_BUG_CATCHING_CONTESTANT_10B
	const EVENT_ROUTE_36_SUDOWOODO
	const EVENT_FLORIA_AT_SUDOWOODO
	const EVENT_FLORIA_AT_FLOWER_SHOP
	const EVENT_GOLDENROD_UNDERGROUND_GRAMPS
	const EVENT_GOLDENROD_UNDERGROUND_GRANNY
	const EVENT_GOLDENROD_UNDERGROUND_OLDER_HAIRCUT_BROTHER
	const EVENT_GOLDENROD_UNDERGROUND_YOUNGER_HAIRCUT_BROTHER
	const EVENT_GOLDENROD_SALE_OFF
	const EVENT_GOLDENROD_SALE_ON
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_TEACHER_BEHIND_COUNTER
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_TEACHER_IN_WALKWAY
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_LASS
	const EVENT_ILEX_FOREST_LASS
	const EVENT_ILEX_FOREST_KURT
;	const EVENT_ILEX_FOREST_FARFETCHD
;	const EVENT_ILEX_FOREST_APPRENTICE
;	const EVENT_ILEX_FOREST_CHARCOAL_MASTER
	const EVENT_AZALEA_TOWN_KURT
	const EVENT_KURTS_HOUSE_KURT_1
	const EVENT_KURTS_HOUSE_KURT_2
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_1
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_2
;	const EVENT_CHARCOAL_KILN_FARFETCH_D
;	const EVENT_CHARCOAL_KILN_APPRENTICE
;	const EVENT_CHARCOAL_KILN_BOSS
	const EVENT_UNION_CAVE_B2F_LAPRAS
	const EVENT_RUINS_OF_ALPH_KABUTO_CHAMBER_SCIENTIST
	const EVENT_RUINS_OF_ALPH_OUTSIDE_SCIENTIST
	const EVENT_RUINS_OF_ALPH_INNER_CHAMBER_SCIENTISTS
	const EVENT_MR_POKEMONS_HOUSE_OAK
	const EVENT_MR_POKEMONS_HOUSE_MR_POKEMON
	const EVENT_NEW_BARK_TOWN_RIVAL
	const EVENT_ELMS_LAB_ELM
;	const EVENT_GOLDENROD_CITY_ROCKET_TAKEOVER
	const EVENT_RADIO_TOWER_4F_OAK
	const EVENT_RADIO_TOWER_3F_BLUE
	const EVENT_RADIO_TOWER_4F_BLUE
	const EVENT_RADIO_TOWER_4F_OFFICER
	const EVENT_RADIO_TOWER_ROCKET_TAKEOVER
	const EVENT_RADIO_TOWER_CIVILIANS
	const EVENT_RADIO_TOWER_CIVILIANS_AFTER

	const EVENT_MAHOGANY_MART_GRANNY
	const EVENT_MAHOGANY_MART_NINJA
	const EVENT_NINJA_SECURITY_NINJAS
	const EVENT_TEAM_ROCKET_BASE_B2F_JANINE
	const EVENT_TEAM_ROCKET_BASE_B2F_KOGA
	const EVENT_TEAM_ROCKET_BASE_B2F_JONIN
	const EVENT_TEAM_ROCKET_BASE_B2F_SPEED_NINJA1
	const EVENT_TEAM_ROCKET_BASE_B2F_SPEED_NINJA2
	const EVENT_TEAM_ROCKET_BASE_B3F_JANINE_NINJA
	const EVENT_TEAM_ROCKET_BASE_B3F_KOGA_NINJA
	const EVENT_TEAM_ROCKET_BASE_B3F_JANINE
	const EVENT_TEAM_ROCKET_BASE_B3F_KOGA
	const EVENT_BLACKTHORN_CITY_GRAMPS_BLOCKS_DRAGONS_DEN
	const EVENT_BLACKTHORN_CITY_GRAMPS_NOT_BLOCKING_DRAGONS_DEN
	const EVENT_DRAGON_SHRINE_DRATINI_POKEBALL
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_BLOCK
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_BATTLE
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_WANDER
;
	const EVENT_LAKE_OF_RAGE_GOLD_MAGIKARP
	const_skip ;EVENT_LAKE_OF_RAGE_CLAIR
;
	const EVENT_BATTLE_TOWER_BATTLE_ROOM_YOUNGSTER
	const EVENT_TIN_TOWER_ROOF_HO_OH
	const EVENT_WHIRL_ISLAND_LUGIA_CHAMBER_LUGIA
	const EVENT_OAK_IN_MT_SILVER
	const EVENT_MT_SILVER_DUMMY_PLAYER
	const EVENT_SILVER_MIRROR
;
; will use?
	const EVENT_ROUTE_37_SUNNY_OF_SUNDAY
	const EVENT_ROUTE_40_MONICA_OF_MONDAY
	const EVENT_ROUTE_29_TUSCANY_OF_TUESDAY
	const EVENT_LAKE_OF_RAGE_WESLEY_OF_WEDNESDAY
	const EVENT_ROUTE_36_ARTHUR_OF_THURSDAY
	const EVENT_ROUTE_32_FRIEDA_OF_FRIDAY
	const EVENT_BLACKTHORN_CITY_SANTOS_OF_SATURDAY
;
	const EVENT_GOLDENROD_CITY_MOVE_TUTOR
	const EVENT_GOLDENROD_GAME_CORNER_MOVE_TUTOR
;
; misc
	const EVENT_PLAYERS_HOUSE_2F_CONSOLE
	const EVENT_PLAYERS_HOUSE_2F_DOLL_1
	const EVENT_PLAYERS_HOUSE_2F_DOLL_2
	const EVENT_PLAYERS_HOUSE_2F_BIG_DOLL
;
; not worth the trouble to remove?
	const EVENT_MYSTERY_GIFT_DELIVERY_GUY
;
; used 86
; running total 549

; OG JOHTO PEOPLE
;	const EVENT_LAKE_OF_RAGE_LANCE
;	const EVENT_MAHOGANY_MART_LANCE_AND_DRAGONITE
;	const EVENT_TEAM_ROCKET_BASE_B2F_LANCE
;	const EVENT_TEAM_ROCKET_BASE_B3F_LANCE_PASSWORDS
;	const EVENT_DRAGONS_DEN_CLAIR
;	const EVENT_TEAM_ROCKET_BASE_POPULATION
;	const EVENT_ROUTE_43_GATE_ROCKETS
;	const EVENT_TEAM_ROCKET_BASE_B2F_EXECUTIVE
;	const EVENT_TEAM_ROCKET_BASE_B2F_GRUNT_WITH_EXECUTIVE
;	const EVENT_TEAM_ROCKET_BASE_B2F_DRAGONITE
;	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_1
;	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_2
;	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_3
;	const EVENT_BLACKTHORN_CITY_SUPER_NERD_BLOCKS_GYM
;	const EVENT_BLACKTHORN_CITY_SUPER_NERD_DOES_NOT_BLOCK_GYM
;	const EVENT_AZALEA_TOWN_SLOWPOKES
;	const EVENT_AZALEA_TOWN_SLOWPOKETAIL_ROCKET
;	const EVENT_KURTS_HOUSE_SLOWPOKE
;	const EVENT_GUIDE_GENT_IN_HIS_HOUSE
;	const EVENT_GUIDE_GENT_VISIBLE_IN_CHERRYGROVE
;	const EVENT_ELMS_AIDE_IN_VIOLET_POKEMON_CENTER
;	const EVENT_ECRUTEAK_POKE_CENTER_BILL
;	const EVENT_ROUTE_30_BATTLE
;	const EVENT_ROUTE_30_YOUNGSTER_JOEY
;	const EVENT_LAKE_OF_RAGE_CIVILIANS
;	const EVENT_OLIVINE_PORT_SPRITES_BEFORE_HALL_OF_FAME
;	const EVENT_OLIVINE_PORT_SPRITES_AFTER_HALL_OF_FAME
;	const EVENT_TEAM_ROCKET_DISBANDED
;	const EVENT_GOLDENROD_DEPT_STORE_5F_HAPPINESS_EVENT_LADY
;	const EVENT_BURNED_TOWER_MORTY
;	const EVENT_RANG_CLEAR_BELL_1
;	const EVENT_RANG_CLEAR_BELL_2
; 133 originals left
;	const EVENT_OLIVINE_LIGHTHOUSE_JASMINE
;	const EVENT_OLIVINE_GYM_JASMINE
;	const EVENT_OLIVINE_PORT_SAILOR_AT_GANGWAY
;	const EVENT_OLIVINE_PORT_PASSAGE_POKEFAN_M
;	const EVENT_RIVAL_TEAM_ROCKET_BASE
;	const EVENT_RIVAL_GOLDENROD_UNDERGROUND
;	const EVENT_DAY_CARE_MAN_ON_ROUTE_34
;	const EVENT_MET_BILL
;	const EVENT_RIVAL_DRAGONS_DEN
;	const EVENT_VIOLET_CITY_EARL
;	const EVENT_EARLS_ACADEMY_EARL
;	const EVENT_GOLDENROD_CITY_ROCKET_SCOUT
;	const EVENT_RADIO_TOWER_BLACKBELT_BLOCKS_STAIRS
;	const EVENT_SLOWPOKE_WELL_SLOWPOKES
;	const EVENT_SLOWPOKE_WELL_ROCKETS
;	const EVENT_FAST_SHIP_CABINS_NNW_NNE_NE_SAILOR
;	const EVENT_FAST_SHIP_CABINS_SE_SSE_GENTLEMAN
;	const EVENT_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_TWIN_1
;	const EVENT_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_TWIN_2
;	const EVENT_SLOWPOKE_WELL_KURT
;	const EVENT_LANCES_ROOM_OAK_AND_MARY
; with OG
; group total used 179
; running total 579

;	const_next 600
; Kanto itemballs
; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.
	const EVENT_CHARMANDER_POKEBALL_IN_OAKS_LAB
	const EVENT_SQUIRTLE_POKEBALL_IN_OAKS_LAB
	const EVENT_BULBASAUR_POKEBALL_IN_OAKS_LAB
	const EVENT_ROUTE_2_HP_UP
	const EVENT_ROUTE_2_MOON_STONE
	const EVENT_VIRIDIAN_FOREST_ANTIDOTE
	const EVENT_VIRIDIAN_FOREST_POTION
	const EVENT_VIRIDIAN_FOREST_POKE_BALL
	const EVENT_VIRIDIAN_FOREST_SILVER_POWDER
	const EVENT_VIRIDIAN_FOREST_TM_SILVER_WIND
	const EVENT_MT_MOON_MOON_STONE
	const EVENT_MT_MOON_POTION1
	const EVENT_MT_MOON_ESCAPE_ROPE
	const EVENT_MT_MOON_RARE_CANDY
	const EVENT_MT_MOON_TM_WATER_GUN
	const EVENT_MT_MOON_POTION2
	const EVENT_MT_MOON_B2F_TM_MUD_SLAP
	const EVENT_MT_MOON_B2F_HP_UP
	const EVENT_ROUTE_4_TM_FALSE_SWIPE
	const EVENT_ROUTE_24_TM_THUNDER_WAVE
	const EVENT_ROUTE_25_TM_SEISMIC_TOSS
	const EVENT_ROUTE_5_SILK_SCARF
	const EVENT_SS_ANNE_ROOMS_NORTH_TM_BODY_SLAM
	const EVENT_SS_ANNE_ROOMS_SOUTH_TM_REST
	const EVENT_SS_ANNE_ROOMS_SOUTH_ETHER
	const EVENT_SS_ANNE_ROOMS_SOUTH_MAX_POTION
	const EVENT_SS_ANNE_ROOMS_2F_MAX_ETHER
	const EVENT_SS_ANNE_ROOMS_2F_RARE_CANDY
	const EVENT_DIGLETTS_CAVE_SOFT_SAND
	const EVENT_ROUTE_9_TM_ENDURE
	const EVENT_ROCK_TUNNEL_1F_HARD_STONE
	const EVENT_ROCK_TUNNEL_B1F_ESCAPE_ROPE
	const EVENT_ROCK_TUNNEL_B1F_TM_GYRO_BALL
	const EVENT_POKEMON_TOWER_5F_CLEANSE_TAG
	const EVENT_ROUTE_12_TM_PAY_DAY
	const EVENT_ROUTE_12_IRON
	const EVENT_CELADON_CITY_MIRACLE_SEED
	const EVENT_CELADON_GAME_CORNER_AMULET_COIN
	const EVENT_ROCKET_HIDEOUT_B1F_TM_THIEF
	const EVENT_ROCKET_HIDEOUT_B1F_ESCAPE_ROPE
	const EVENT_ROCKET_HIDEOUT_B1F_HYPER_POTION
	const EVENT_ROCKET_HIDEOUT_B2F_NUGGET
	const EVENT_ROCKET_HIDEOUT_B2F_MOON_STONE
	const EVENT_ROCKET_HIDEOUT_B2F_TM_SHARPEN
	const EVENT_ROCKET_HIDEOUT_B2F_SUPER_POTION
	const EVENT_ROCKET_HIDEOUT_B3F_RARE_CANDY
	const EVENT_ROCKET_HIDEOUT_B3F_TM_DOUBLE_EDGE
	const EVENT_ROCKET_HIDEOUT_B4F_LIFT_KEY
	const EVENT_ROCKET_HIDEOUT_B4F_TM_AIR_SLICE
	const EVENT_ROCKET_HIDEOUT_B4F_HP_UP
	const EVENT_ROCKET_HIDEOUT_B4F_IRON
	const EVENT_ROCKET_HIDEOUT_B4F_SILPH_SCOPE
	const EVENT_POKEMON_TOWER_3F_ESCAPE_ROPE
	const EVENT_POKEMON_TOWER_4F_AWAKENING
	const EVENT_POKEMON_TOWER_4F_ELIXER
	const EVENT_POKEMON_TOWER_4F_HP_UP
	const EVENT_POKEMON_TOWER_5F_NUGGET
	const EVENT_POKEMON_TOWER_6F_X_ACCURACY
	const EVENT_POKEMON_TOWER_6F_RARE_CANDY
	const EVENT_POKEMON_TOWER_6F_SPELL_TAG
	const EVENT_ROUTE_12_TM_SNORE
	const EVENT_ROUTE_15_TM_WATER_PULSE
	const EVENT_ROUTE_16_TM_AERIAL_ACE
	const EVENT_ROUTE_17_SHARP_BEAK
	const EVENT_ROUTE_17_TM_ROLLOUT
	const EVENT_SAFARI_WARDENS_HOUSE_RARE_CANDY
	const EVENT_SAFARI_ZONE_AREA_1_NUGGET
	const EVENT_SAFARI_ZONE_AREA_2_MAX_POTION
	const EVENT_SAFARI_ZONE_AREA_2_FULL_RESTORE
	const EVENT_SAFARI_ZONE_AREA_2_TM_BULLET_SEED
	const EVENT_SAFARI_ZONE_AREA_2_CARBOS
	const EVENT_SAFARI_ZONE_AREA_3_PROTEIN
	const EVENT_SAFARI_ZONE_AREA_3_TM_POISON_JAB
	const EVENT_SAFARI_ZONE_AREA_4_TM_ROOST
	const EVENT_SAFARI_ZONE_AREA_4_GOLD_TEETH
	const EVENT_SAFARI_ZONE_AREA_4_MAX_REVIVE
	const EVENT_SAFARI_ZONE_AREA_4_MAX_POTION
	const EVENT_ROUTE_19_POISON_BARB
	const EVENT_ROUTE_20_TM_BRICK_BREAK
	const EVENT_MR_PSYCHICS_HOUSE_TWISTED_SPOON
	const EVENT_SILPH_CO_3F_HYPER_POTION
	const EVENT_SILPH_CO_4F_FULL_HEAL
	const EVENT_SILPH_CO_4F_MAX_REVIVE
	const EVENT_SILPH_CO_4F_ESCAPE_ROPE
	const EVENT_SILPH_CO_5F_PROTEIN
	const EVENT_SILPH_CO_5F_TM_SUBMISSION
	const EVENT_SILPH_CO_5F_CARD_KEY
	const EVENT_SILPH_CO_6F_HP_UP
	const EVENT_SILPH_CO_6F_X_ACCURACY
	const EVENT_SILPH_CO_7F_CALCIUM
	const EVENT_SILPH_CO_7F_TM_SWORDS_DANCE
	const EVENT_SILPH_CO_10F_CARBOS
	const EVENT_SILPH_CO_10F_TM_EARTHQUAKE
	const EVENT_SILPH_CO_10F_RARE_CANDY
	const EVENT_FIGHTING_DOJO_FOCUS_BAND
	const EVENT_FIGHTING_DOJO_BLACK_BELT
	const EVENT_POKEMON_MANSION_1F_CHARCOAL
	const EVENT_POKEMON_MANSION_1F_ESCAPE_ROPE
	const EVENT_POKEMON_MANSION_1F_CARBOS
	const EVENT_POKEMON_MANSION_2F_CALCIUM
	const EVENT_POKEMON_MANSION_3F_IRON
	const EVENT_POKEMON_MANSION_3F_MAX_POTION
	const EVENT_POKEMON_MANSION_B1F_RARE_CANDY
	const EVENT_POKEMON_MANSION_B1F_TM_SOLARBEAM
	const EVENT_POKEMON_MANSION_B1F_FULL_RESTORE
	const EVENT_POKEMON_MANSION_B1F_TM_BLIZZARD
	const EVENT_VIRIDIAN_GYM_REVIVE
	const EVENT_ROUTE_26_MAX_ELIXER
	const EVENT_VICTORY_ROAD_1F_TM_DRAGON_CLAW
	const EVENT_VICTORY_ROAD_1F_RARE_CANDY
	const EVENT_VICTORY_ROAD_2F_GUARD_SPEC
	const EVENT_VICTORY_ROAD_2F_TM_FOCUS_BLAST
	const EVENT_VICTORY_ROAD_2F_FULL_HEAL
	const EVENT_VICTORY_ROAD_2F_TM_SHADOW_CLAW
	const EVENT_VICTORY_ROAD_3F_TM_SLUDGE_BOMB
	const EVENT_VICTORY_ROAD_3F_MAX_REVIVE
	const EVENT_SEAFOAM_B4F_NEVERMELTICE
	const EVENT_SEAFOAM_B4F_TM_ICE_BEAM
	const EVENT_POWER_PLANT_TM_THUNDERBOLT
	const EVENT_VICTORY_ROAD_2F_TM_FLAMETHROWER
	const EVENT_ROUTE_10_MAGNET
	const EVENT_POWER_PLANT_TM_REFLECT
	const EVENT_POWER_PLANT_TM_THUNDER
	const EVENT_POWER_PLANT_VOLTORB_1
	const EVENT_POWER_PLANT_VOLTORB_2
	const EVENT_POWER_PLANT_VOLTORB_3
	const EVENT_POWER_PLANT_VOLTORB_4
	const EVENT_POWER_PLANT_VOLTORB_5
	const EVENT_POWER_PLANT_VOLTORB_6
	const EVENT_POWER_PLANT_ELECTRODE_1
	const EVENT_POWER_PLANT_ELECTRODE_2
	const EVENT_POWER_PLANT_CARBOS
	const EVENT_POWER_PLANT_RARE_CANDY
	const EVENT_POWER_PLANT_HP_UP
	const EVENT_CERULEAN_CAVE_1F_NUGGET
	const EVENT_CERULEAN_CAVE_1F_FULL_RESTORE
	const EVENT_CERULEAN_CAVE_1F_MAX_ELIXER
	const EVENT_CERULEAN_CAVE_2F_PP_UP
	const EVENT_CERULEAN_CAVE_2F_ULTRA_BALL
	const EVENT_CERULEAN_CAVE_2F_FULL_RESTORE
	const EVENT_CERULEAN_CAVE_2F_SCOPE_LENS
	const EVENT_CERULEAN_CAVE_B1F_ULTRA_BALL
	const EVENT_CERULEAN_CAVE_B1F_MAX_REVIVE
	const EVENT_CERULEAN_CAVE_B1F_BERSERK_GENE
	const EVENT_ROUTE_27_RARE_CANDY
; used 145
; running total used 745
;
; Johto itemballs
; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.
	const EVENT_OLIVINE_LIGHTHOUSE_6F_METAL_COAT
	const EVENT_BURNED_TOWER_1F_HP_UP
	const EVENT_BURNED_TOWER_1F_DUSK_STONE
;	const EVENT_ROUTE_42_ULTRA_BALL
	const EVENT_ROUTE_42_MAX_POTION
	const EVENT_MOUNT_MORTAR_1F_OUTSIDE_ETHER
	const EVENT_MOUNT_MORTAR_1F_OUTSIDE_REVIVE
	const EVENT_MOUNT_MORTAR_1F_INSIDE_ESCAPE_ROPE
	const EVENT_MOUNT_MORTAR_1F_INSIDE_MAX_REVIVE
	const EVENT_MOUNT_MORTAR_1F_INSIDE_HYPER_POTION
	const EVENT_MOUNT_MORTAR_1F_INSIDE_MAX_POTION
	const EVENT_MOUNT_MORTAR_1F_INSIDE_NUGGET
	const EVENT_MOUNT_MORTAR_1F_INSIDE_IRON
	const EVENT_MOUNT_MORTAR_1F_INSIDE_ULTRA_BALL
	const EVENT_MOUNT_MORTAR_2F_INSIDE_MAX_POTION
	const EVENT_MOUNT_MORTAR_2F_INSIDE_RARE_CANDY
	const EVENT_MOUNT_MORTAR_2F_INSIDE_TM_STONE_EDGE
	const EVENT_MOUNT_MORTAR_2F_INSIDE_DRAGON_SCALE
	const EVENT_MOUNT_MORTAR_2F_INSIDE_ELIXER
	const EVENT_MOUNT_MORTAR_2F_INSIDE_ESCAPE_ROPE
	const EVENT_MOUNT_MORTAR_B1F_HYPER_POTION
	const EVENT_MOUNT_MORTAR_B1F_CARBOS
	const EVENT_MOUNT_MORTAR_B1F_FULL_RESTORE
	const EVENT_MOUNT_MORTAR_B1F_MAX_ETHER
	const EVENT_MOUNT_MORTAR_B1F_PP_UP
	const EVENT_NATIONAL_PARK_SUN_STONE
	const EVENT_NATIONAL_PARK_TM_ENERGY_BALL
	const EVENT_GOLDENROD_DEPT_STORE_B1F_ETHER
	const EVENT_GOLDENROD_DEPT_STORE_B1F_BURN_HEAL
	const EVENT_GOLDENROD_DEPT_STORE_B1F_ULTRA_BALL
	const EVENT_GOLDENROD_DEPT_STORE_B1F_AMULET_COIN
	const EVENT_ROUTE_34_NUGGET
	const EVENT_ILEX_FOREST_REVIVE
	const EVENT_ILEX_FOREST_X_ATTACK
	const EVENT_ILEX_FOREST_ANTIDOTE
	const EVENT_ILEX_FOREST_ETHER
	const EVENT_UNION_CAVE_1F_ULTRA_BALL
	const EVENT_UNION_CAVE_1F_MAX_POTION
	const EVENT_UNION_CAVE_1F_RARE_CANDY
	const EVENT_UNION_CAVE_B1F_X_DEFEND
	const EVENT_ROUTE_32_ULTRA_BALL
	const EVENT_ROUTE_32_MAX_REPEL
	const EVENT_VIOLET_CITY_PP_UP
	const EVENT_VIOLET_CITY_RARE_CANDY
	const EVENT_ROUTE_30_RAINBOW_WING
	const EVENT_UNION_CAVE_B2F_ELIXER
	const EVENT_UNION_CAVE_B2F_HYPER_POTION
	const EVENT_SPROUT_TOWER_1F_PARLYZ_HEAL
	const EVENT_SPROUT_TOWER_2F_X_ACCURACY
	const EVENT_SPROUT_TOWER_3F_POTION
	const EVENT_SPROUT_TOWER_3F_ESCAPE_ROPE
	const EVENT_ROUTE_29_POTION
	const EVENT_ROUTE_31_POTION
	const EVENT_ROUTE_31_POKE_BALL
	const EVENT_TOHJO_FALLS_MOON_STONE
	const EVENT_RADIO_TOWER_5F_ULTRA_BALL
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_TM_DARK_PULSE
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_FULL_HEAL
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_HYPER_POTION
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_DIRE_HIT
	const EVENT_DARK_CAVE_BLACKTHORN_ENTRANCE_REVIVE
	const EVENT_DARK_CAVE_BLACKTHORN_ENTRANCE_LINKING_CORD
	const EVENT_ROUTE_45_NUGGET
	const EVENT_ROUTE_45_REVIVE
	const EVENT_ROUTE_45_ELIXER
	const EVENT_ROUTE_45_MAX_POTION
	const EVENT_ROUTE_46_X_SPEED
	const EVENT_ICE_PATH_1F_PP_UP
	const EVENT_ICE_PATH_1F_PROTEIN
	const EVENT_ICE_PATH_B1F_IRON
	const EVENT_ICE_PATH_B2F_MAHOGANY_SIDE_FULL_HEAL
	const EVENT_ICE_PATH_B2F_MAHOGANY_SIDE_MAX_POTION
	const EVENT_ICE_PATH_B2F_BLACKTHORN_SIDE_TM_FLASH_CANNON
	const EVENT_ROUTE_44_MAX_REVIVE
	const EVENT_ROUTE_44_ULTRA_BALL
	const EVENT_ROUTE_44_MAX_REPEL
	const EVENT_TEAM_ROCKET_BASE_B1F_HYPER_POTION
	const EVENT_TEAM_ROCKET_BASE_B1F_NUGGET
	const EVENT_TEAM_ROCKET_BASE_B1F_GUARD_SPEC
	const EVENT_TEAM_ROCKET_BASE_B2F_TM_THIEF
	const EVENT_TEAM_ROCKET_BASE_B3F_PROTEIN
	const EVENT_TEAM_ROCKET_BASE_B3F_X_SPECIAL
	const EVENT_TEAM_ROCKET_BASE_B3F_FULL_HEAL
	const EVENT_TEAM_ROCKET_BASE_B3F_ULTRA_BALL
	const EVENT_ROUTE_43_MAX_ETHER
	const EVENT_LAKE_OF_RAGE_ELIXER
	const EVENT_DRAGONS_DEN_B1F_CALCIUM
	const EVENT_DRAGONS_DEN_B1F_MAX_ELIXER
	const EVENT_DRAGONS_DEN_B1F_TM_DRAGON_PULSE
	const EVENT_DRAGONS_DEN_B1F_DRAGON_FANG
	const EVENT_TIN_TOWER_3F_FULL_HEAL
	const EVENT_TIN_TOWER_4F_ULTRA_BALL
	const EVENT_TIN_TOWER_4F_PP_UP
	const EVENT_TIN_TOWER_4F_ESCAPE_ROPE
	const EVENT_TIN_TOWER_5F_RARE_CANDY
	const EVENT_TIN_TOWER_6F_MAX_POTION
	const EVENT_TIN_TOWER_7F_MAX_REVIVE
	const EVENT_TIN_TOWER_8F_NUGGET
	const EVENT_TIN_TOWER_8F_MAX_ELIXER
	const EVENT_TIN_TOWER_8F_FULL_RESTORE
	const EVENT_TIN_TOWER_9F_HP_UP
	const EVENT_WHIRL_ISLAND_NE_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_SW_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_B1F_FULL_RESTORE
	const EVENT_WHIRL_ISLAND_B1F_CARBOS
	const EVENT_WHIRL_ISLAND_B1F_CALCIUM
	const EVENT_WHIRL_ISLAND_B1F_NUGGET
	const EVENT_WHIRL_ISLAND_B1F_ESCAPE_ROPE
	const EVENT_WHIRL_ISLAND_B2F_FULL_RESTORE
	const EVENT_WHIRL_ISLAND_B2F_MAX_REVIVE
	const EVENT_WHIRL_ISLAND_B2F_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_1_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_PROTEIN
	const EVENT_SILVER_CAVE_ROOM_1_ESCAPE_ROPE
	const EVENT_SILVER_CAVE_ROOM_2_CALCIUM
	const EVENT_SILVER_CAVE_ROOM_2_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_PP_UP
	const EVENT_SILVER_CAVE_ITEM_ROOMS_MAX_REVIVE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_FULL_RESTORE
;
; original itemballs
;	const EVENT_CYNDAQUIL_POKEBALL_IN_ELMS_LAB
;	const EVENT_TOTODILE_POKEBALL_IN_ELMS_LAB
;	const EVENT_CHIKORITA_POKEBALL_IN_ELMS_LAB
;	const EVENT_LAKE_OF_RAGE_TM_DETECT
;	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_ULTRA_BALL
;	const EVENT_BURNED_TOWER_B1F_TM_ENDURE
;	const EVENT_UNION_CAVE_B1F_TM_SWIFT
;	const EVENT_SLOWPOKE_WELL_B1F_SUPER_POTION
;	const EVENT_SLOWPOKE_WELL_B2F_TM_RAIN_DANCE
;	const EVENT_OLIVINE_LIGHTHOUSE_3F_ETHER
;	const EVENT_OLIVINE_LIGHTHOUSE_5F_RARE_CANDY
;	const EVENT_OLIVINE_LIGHTHOUSE_5F_SUPER_REPEL
;	const EVENT_OLIVINE_LIGHTHOUSE_5F_TM_SWAGGER

;	const EVENT_TEAM_ROCKET_BASE_B3F_ICE_HEAL
;	const EVENT_GOLDENROD_UNDERGROUND_COIN_CASE
;	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_SMOKE_BALL
;	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_FULL_HEAL
;	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_MAX_ETHER
;	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_TM_SLEEP_TALK
;	const EVENT_ICE_PATH_B3F_NEVERMELTICE
;	const EVENT_ROUTE_27_TM_SOLARBEAM
;	const EVENT_ROUTE_35_TM_ROLLOUT
;	const EVENT_ROUTE_30_ANTIDOTE
;
; used 115
; group total used 260
; running total 860

	const_next 900 ;850
; Kanto hidden items (silvermirror)
	const EVENT_VIRIDIAN_CITY_HIDDEN_POTION                ;done
	const EVENT_VIRIDIAN_FOREST_HIDDEN_POTION              ;done
	const EVENT_VIRIDIAN_FOREST_HIDDEN_ANTIDOTE            ;done
	const EVENT_MT_MOON_B2F_HIDDEN_ETHER                   ;done
	const EVENT_MT_MOON_B2F_HIDDEN_MOON_STONE              ;done
	const EVENT_ROUTE_4_HIDDEN_GREAT_BALL                  ;done
	const EVENT_CERULEAN_CITY_HIDDEN_RARE_CANDY            ;done
	const EVENT_ROUTE_25_HIDDEN_ELIXER                     ;done
	const EVENT_ROUTE_25_HIDDEN_ETHER                      ;done
	const EVENT_ROUTE_5_HIDDEN_EVERSTONE                   ;new in silvermirror
	const EVENT_UNDERGROUND_PATH_NS_HIDDEN_FULL_RESTORE    ;done
	const EVENT_UNDERGROUND_PATH_NS_HIDDEN_X_SPECIAL       ;done
	const EVENT_ROUTE_11_HIDDEN_ESCAPE_ROPE                ;done
	const EVENT_ROUTE_12_HIDDEN_HYPER_POTION               ;done
	const EVENT_SS_ANNE_B1F_HIDDEN_HYPER_POTION            ;done
	const EVENT_SS_ANNE_KITCHEN_HIDDEN_GREAT_BALL          ;done
	const EVENT_ROUTE_9_HIDDEN_ETHER                       ;done
	const EVENT_ROUTE_10_HIDDEN_SUPER_POTION               ;done
	const EVENT_ROUTE_10_HIDDEN_MAX_ETHER                  ;done
	const EVENT_UNDERGROUND_PATH_EW_HIDDEN_NUGGET          ;done
	const EVENT_UNDERGROUND_PATH_EW_HIDDEN_ELIXER          ;done
	const EVENT_CELADON_CITY_HIDDEN_PP_UP                  ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_10_1      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_10_2      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_10_3      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_10_4      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_10_5      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_10_6      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_10_7      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_10_8      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_20_1      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_20_2      ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_40        ;done
	const EVENT_CELADON_GAME_CORNER_HIDDEN_COINS_100       ;done
	const EVENT_ROCKET_HIDEOUT_B1F_HIDDEN_PP_UP            ;done
	const EVENT_ROCKET_HIDEOUT_B3F_HIDDEN_NUGGET           ;done
	const EVENT_ROCKET_HIDEOUT_B4F_HIDDEN_SUPER_POTION     ;done
	const EVENT_POKEMON_TOWER_5F_HIDDEN_ELIXER             ;done
	const EVENT_ROUTE_13_HIDDEN_CALCIUM                    ;done
	const EVENT_ROUTE_13_HIDDEN_PP_UP                      ;done
	const EVENT_ROUTE_17_HIDDEN_RARE_CANDY                 ;done
	const EVENT_ROUTE_17_HIDDEN_FULL_RESTORE               ;done
	const EVENT_ROUTE_17_HIDDEN_MAX_REVIVE                 ;done
	const EVENT_ROUTE_17_HIDDEN_PP_UP                      ;done
	const EVENT_ROUTE_17_HIDDEN_MAX_ELIXER                 ;done
	const EVENT_SAFARI_ZONE_WEST_HIDDEN_REVIVE             ;done
	const EVENT_VERMILION_CITY_HIDDEN_MAX_ETHER            ;done
	const EVENT_POWER_PLANT_HIDDEN_MAX_ELIXER              ;done
	const EVENT_POWER_PLANT_HIDDEN_PP_UP                   ;done
	const EVENT_SILPH_CO_5F_HIDDEN_ELIXER                  ;done
	const EVENT_SILPH_CO_9F_HIDDEN_MAX_POTION              ;done
	const EVENT_COPYCATS_HOUSE_2F_HIDDEN_NUGGET            ;done
	const EVENT_SEAFOAM_ISLANDS_B2F_HIDDEN_NUGGET          ;done
	const EVENT_SEAFOAM_ISLANDS_B3F_HIDDEN_MAX_ELIXER      ;done
	const EVENT_SEAFOAM_ISLANDS_B4F_HIDDEN_ULTRA_BALL      ;done
	const EVENT_POKEMON_MANSION_1F_HIDDEN_MOON_STONE       ;done
	const EVENT_POKEMON_MANSION_3F_HIDDEN_MAX_REVIVE       ;done
	const EVENT_POKEMON_MANSION_B1F_HIDDEN_RARE_CANDY      ;done
	const EVENT_ROUTE_23_HIDDEN_MAX_ETHER                  ;done
	const EVENT_ROUTE_23_HIDDEN_ULTRA_BALL                 ;done
	const EVENT_ROUTE_23_HIDDEN_FULL_RESTORE               ;done
	const EVENT_VICTORY_ROAD_2F_HIDDEN_ULTRA_BALL          ;done
	const EVENT_VICTORY_ROAD_3F_HIDDEN_FULL_RESTORE        ;done
	const EVENT_CERULEAN_CAVE_1F_HIDDEN_RARE_CANDY         ;done
	const EVENT_CERULEAN_CAVE_2F_HIDDEN_PP_UP              ;done
	const EVENT_CERULEAN_CAVE_B1F_HIDDEN_ULTRA_BALL        ;done
	const EVENT_MT_MOON_SQUARE_HIDDEN_MOON_STONE           ;done (respawns)
; used 67
; running total 967
;
; Johto hidden items
	const EVENT_ROUTE_40_HIDDEN_HYPER_POTION
	const EVENT_ROUTE_41_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_39_HIDDEN_NUGGET
	const EVENT_ECRUTEAK_CITY_HIDDEN_HYPER_POTION
	const EVENT_BURNED_TOWER_1F_HIDDEN_ETHER
	const EVENT_BURNED_TOWER_1F_HIDDEN_ULTRA_BALL
	const EVENT_ROUTE_42_HIDDEN_MAX_POTION
	const EVENT_MOUNT_MORTAR_1F_OUTSIDE_HIDDEN_HYPER_POTION
	const EVENT_MOUNT_MORTAR_1F_INSIDE_HIDDEN_MAX_REPEL
	const EVENT_MOUNT_MORTAR_2F_INSIDE_HIDDEN_FULL_RESTORE
	const EVENT_MOUNT_MORTAR_B1F_HIDDEN_MAX_REVIVE
	const EVENT_ROUTE_37_HIDDEN_ETHER
	const EVENT_NATIONAL_PARK_HIDDEN_FULL_HEAL
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_REVIVAL_HERB
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_MAX_POTION
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_RARE_CANDY
	const EVENT_ROUTE_34_HIDDEN_MAX_POTION
	const EVENT_ROUTE_34_HIDDEN_RARE_CANDY
	const EVENT_ILEX_FOREST_HIDDEN_ETHER
	const EVENT_ILEX_FOREST_HIDDEN_HYPER_POTION
	const EVENT_ILEX_FOREST_HIDDEN_FULL_HEAL
	const EVENT_AZALEA_TOWN_HIDDEN_FULL_HEAL
	const EVENT_ROUTE_32_HIDDEN_ULTRA_BALL
	const EVENT_ROUTE_32_HIDDEN_MAX_POTION
	const EVENT_VIOLET_CITY_HIDDEN_HYPER_POTION
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_HIDDEN_ELIXER
	const EVENT_ROUTE_45_HIDDEN_PP_UP
	const EVENT_ICE_PATH_B1F_HIDDEN_MAX_POTION
	const EVENT_ICE_PATH_B2F_MAHOGANY_SIDE_HIDDEN_CARBOS
	const EVENT_ROUTE_44_HIDDEN_ELIXER
	const EVENT_CIANWOOD_CITY_HIDDEN_REVIVE
	const EVENT_CIANWOOD_CITY_HIDDEN_MAX_ETHER
	const EVENT_TEAM_ROCKET_BASE_B1F_HIDDEN_REVIVE
	const EVENT_TEAM_ROCKET_BASE_B2F_HIDDEN_FULL_HEAL
	const EVENT_LAKE_OF_RAGE_HIDDEN_FULL_RESTORE
	const EVENT_LAKE_OF_RAGE_HIDDEN_RARE_CANDY
	const EVENT_LAKE_OF_RAGE_HIDDEN_MAX_POTION
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_REVIVE
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_POTION
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_ELIXER
	const EVENT_TIN_TOWER_4F_HIDDEN_MAX_POTION
	const EVENT_TIN_TOWER_5F_HIDDEN_FULL_RESTORE
	const EVENT_TIN_TOWER_5F_HIDDEN_CARBOS
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_RARE_CANDY
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_FULL_RESTORE
	const EVENT_ROUTE_28_HIDDEN_RARE_CANDY
	const EVENT_SILVER_CAVE_OUTSIDE_HIDDEN_FULL_RESTORE
	const EVENT_SILVER_CAVE_ROOM_1_HIDDEN_DIRE_HIT
	const EVENT_SILVER_CAVE_ROOM_1_HIDDEN_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_HIDDEN_MAX_POTION
;
; in place above this line
;
;	const EVENT_OLIVINE_LIGHTHOUSE_5F_HIDDEN_HYPER_POTION
;	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HIDDEN_MAX_POTION
;	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HIDDEN_REVIVE
;	const EVENT_ICE_PATH_B2F_BLACKTHORN_SIDE_HIDDEN_ICE_HEAL
;	const EVENT_ROUTE_30_HIDDEN_POTION

; used 51
; group total used 118
; running total used 1018

	const_next 1050
; Trainer flags
; Johto Gym Leaders
	const EVENT_BEAT_FALKNER
	const EVENT_BEAT_BUGSY
	const EVENT_BEAT_WHITNEY
	const EVENT_BEAT_MORTY
	const EVENT_BEAT_CHUCK
	const EVENT_BEAT_JASMINE
	const EVENT_BEAT_PRYCE
	const EVENT_BEAT_CLAIR
; Kanto Gym Leaders
	const EVENT_BEAT_BROCK
	const EVENT_BEAT_MISTY
	const EVENT_BEAT_LTSURGE
	const EVENT_BEAT_ERIKA
	const EVENT_BEAT_KOGA
	const EVENT_BEAT_SABRINA
	const EVENT_BEAT_BLAINE
	const EVENT_BEAT_GIOVANNI
; Giovanni
	const EVENT_BEAT_GIOVANNI_HIDEOUT
	const EVENT_BEAT_GIOVANNI_SILPHCO
; Elite Four and Champion
	const EVENT_BEAT_E4_LORELEI
	const EVENT_BEAT_E4_BRUNO
	const EVENT_BEAT_E4_AGATHA
	const EVENT_BEAT_E4_LANCE
	const EVENT_BEAT_E4_CHAMPION
; Cal
	const EVENT_BEAT_ROUTE_29_CAL
; Mt Silver
	const EVENT_BEAT_MT_SILVER_OAK
; GruntM
	const EVENT_BEAT_GRUNTM_1
	const EVENT_BEAT_GRUNTM_2
	const EVENT_BEAT_GRUNTM_3
	const EVENT_BEAT_GRUNTM_4
	const EVENT_BEAT_GRUNTM_5
	const EVENT_BEAT_GRUNTM_6
	const EVENT_BEAT_GRUNTM_7
	const EVENT_BEAT_GRUNTM_8
	const EVENT_BEAT_GRUNTM_9
	const EVENT_BEAT_GRUNTM_10
	const EVENT_BEAT_GRUNTM_11
	const EVENT_BEAT_GRUNTM_12
	const EVENT_BEAT_GRUNTM_13
	const EVENT_BEAT_GRUNTM_14
	const EVENT_BEAT_GRUNTM_15
	const EVENT_BEAT_GRUNTM_16
	const EVENT_BEAT_GRUNTM_17
	const EVENT_BEAT_GRUNTM_18
	const EVENT_BEAT_GRUNTM_19
	const EVENT_BEAT_GRUNTM_20
	const EVENT_BEAT_GRUNTM_21
	const EVENT_BEAT_GRUNTM_22
	const EVENT_BEAT_GRUNTM_23
	const EVENT_BEAT_GRUNTM_24
	const EVENT_BEAT_GRUNTM_25
	const EVENT_BEAT_GRUNTM_26
	const EVENT_BEAT_GRUNTM_27
	const EVENT_BEAT_GRUNTM_28
	const EVENT_BEAT_GRUNTM_29
	const EVENT_BEAT_GRUNTM_30
; GruntF
	const EVENT_BEAT_GRUNTF_1
	const EVENT_BEAT_GRUNTF_2
	const EVENT_BEAT_GRUNTF_3
	const EVENT_BEAT_GRUNTF_4
	const EVENT_BEAT_GRUNTF_5
	const EVENT_BEAT_GRUNTF_6
	const EVENT_BEAT_GRUNTF_7
	const EVENT_BEAT_GRUNTF_8
	const EVENT_BEAT_GRUNTF_9
; ExecutiveM
	const EVENT_BEAT_EXECUTIVEM_1
	const EVENT_BEAT_EXECUTIVEM_2
	const EVENT_BEAT_EXECUTIVEM_3
	const EVENT_BEAT_ROCKET_FANATIC
; ExecutiveF
	const EVENT_BEAT_EXECUTIVEF_1
	const EVENT_BEAT_EXECUTIVEF_2
; Scientist
	const EVENT_BEAT_SCIENTIST_ROSS
	const EVENT_BEAT_SCIENTIST_MITCH
	const EVENT_BEAT_SCIENTIST_JED
	const EVENT_BEAT_SCIENTIST_MARC
	const EVENT_BEAT_SCIENTIST_RICH
	const EVENT_BEAT_SCIENTIST_LOWELL
	const EVENT_BEAT_SCIENTIST_DANNIE
	const EVENT_BEAT_SCIENTIST_LINDEN
	const EVENT_BEAT_SCIENTIST_ISAIAH
	const EVENT_BEAT_SCIENTIST_WESTON
	const EVENT_BEAT_SCIENTIST_SILAS
	const EVENT_BEAT_SCIENTIST_DOMINIC
	const EVENT_BEAT_SCIENTIST_EZEKIEL
; Youngster
	const EVENT_BEAT_YOUNGSTER_ASHER
	const EVENT_BEAT_YOUNGSTER_GORDON
	const EVENT_BEAT_YOUNGSTER_ALBERT
	const EVENT_BEAT_YOUNGSTER_SAMUEL
	const EVENT_BEAT_YOUNGSTER_MIKEY
	const EVENT_BEAT_YOUNGSTER_RICKY
	const EVENT_BEAT_YOUNGSTER_JIMMY
	const EVENT_BEAT_YOUNGSTER_OWEN
	const EVENT_BEAT_YOUNGSTER_IAN
	const EVENT_BEAT_YOUNGSTER_JASON
	const EVENT_BEAT_YOUNGSTER_DANNY
	const EVENT_BEAT_YOUNGSTER_REGIS
	const EVENT_BEAT_YOUNGSTER_JOEY
	const EVENT_BEAT_YOUNGSTER_THOMAS
	const EVENT_BEAT_YOUNGSTER_BRADY
; Schoolboy
	const EVENT_BEAT_SCHOOLBOY_BILLY
	const EVENT_BEAT_SCHOOLBOY_ALAN
	const EVENT_BEAT_SCHOOLBOY_TORIN
	const EVENT_BEAT_SCHOOLBOY_CHAD
	const EVENT_BEAT_SCHOOLBOY_JACK
	const EVENT_BEAT_SCHOOLBOY_BRAD
; BirdKeeper
	const EVENT_BEAT_BIRD_KEEPER_ROD
	const EVENT_BEAT_BIRD_KEEPER_ABE
	const EVENT_BEAT_BIRD_KEEPER_ROY
	const EVENT_BEAT_BIRD_KEEPER_JAMIE
	const EVENT_BEAT_BIRD_KEEPER_TOBY
	const EVENT_BEAT_BIRD_KEEPER_DENNIS
	const EVENT_BEAT_BIRD_KEEPER_PERRY
	const EVENT_BEAT_BIRD_KEEPER_HANK
	const EVENT_BEAT_BIRD_KEEPER_THEO
	const EVENT_BEAT_BIRD_KEEPER_BORIS
	const EVENT_BEAT_BIRD_KEEPER_BOB
	const EVENT_BEAT_BIRD_KEEPER_JOSE
	const EVENT_BEAT_BIRD_KEEPER_BRYAN
	const EVENT_BEAT_BIRD_KEEPER_PETER
	const EVENT_BEAT_BIRD_KEEPER_VANCE
	const EVENT_BEAT_BIRD_KEEPER_JOE
	const EVENT_BEAT_BIRD_KEEPER_NATE
	const EVENT_BEAT_BIRD_KEEPER_JOHN
	const EVENT_BEAT_BIRD_KEEPER_RICK
	const EVENT_BEAT_BIRD_KEEPER_LUCAS
; Lass
	const EVENT_BEAT_LASS_BRIDGET
	const EVENT_BEAT_LASS_COLETTE
	const EVENT_BEAT_LASS_EVELYN
	const EVENT_BEAT_LASS_ALICE
	const EVENT_BEAT_LASS_LINDA
	const EVENT_BEAT_LASS_KRISE
	const EVENT_BEAT_LASS_LAURA
	const EVENT_BEAT_LASS_SHANNON
	const EVENT_BEAT_LASS_MICHELLE
	const EVENT_BEAT_LASS_HILLARY
	const EVENT_BEAT_LASS_SADIE
	const EVENT_BEAT_LASS_ELLEN
	const EVENT_BEAT_LASS_DANA
	const EVENT_BEAT_LASS_SARAH
	const EVENT_BEAT_LASS_CHLOE
	const EVENT_BEAT_LASS_NORA
	const EVENT_BEAT_LASS_CORA
	const EVENT_BEAT_LASS_ZOEY
	const EVENT_BEAT_LASS_ELENA
	const EVENT_BEAT_LASS_CONNIE
	const EVENT_BEAT_LASS_HAILEY
	const EVENT_BEAT_LASS_KELLY
	const EVENT_BEAT_LASS_RUBY
; Teacher
	const EVENT_BEAT_TEACHER_KATE
	const EVENT_BEAT_TEACHER_SHIRLEY
	const EVENT_BEAT_TEACHER_IRENE
; CooltrainerM
	const EVENT_BEAT_COOLTRAINERM_PAUL
	const EVENT_BEAT_COOLTRAINERM_NICK
	const EVENT_BEAT_COOLTRAINERM_AARON
	const EVENT_BEAT_COOLTRAINERM_SEAN
	const EVENT_BEAT_COOLTRAINERM_MIKE
	const EVENT_BEAT_COOLTRAINERM_LEVI
	const EVENT_BEAT_COOLTRAINERM_RYAN
	const EVENT_BEAT_COOLTRAINERM_GAVIN
	const EVENT_BEAT_COOLTRAINERM_FINN
	const EVENT_BEAT_COOLTRAINERM_FELIX
	const EVENT_BEAT_COOLTRAINERM_ANDRE
	const EVENT_BEAT_COOLTRAINERM_JAKE
	const EVENT_BEAT_COOLTRAINERM_BRIAN
	const EVENT_BEAT_COOLTRAINERM_KEVIN
	const EVENT_BEAT_COOLTRAINERM_COLT
	const EVENT_BEAT_COOLTRAINERM_ZANE
	const EVENT_BEAT_COOLTRAINERM_AXEL
	const EVENT_BEAT_COOLTRAINERM_MILES
	const EVENT_BEAT_COOLTRAINERM_ADAM
; CooltrainerF
	const EVENT_BEAT_COOLTRAINERF_GWEN
	const EVENT_BEAT_COOLTRAINERF_LOIS
	const EVENT_BEAT_COOLTRAINERF_ANNIE
	const EVENT_BEAT_COOLTRAINERF_FRAN
	const EVENT_BEAT_COOLTRAINERF_JOYCE
	const EVENT_BEAT_COOLTRAINERF_BETH
	const EVENT_BEAT_COOLTRAINERF_MIRA
	const EVENT_BEAT_COOLTRAINERF_MIA
	const EVENT_BEAT_COOLTRAINERF_ELLA
	const EVENT_BEAT_COOLTRAINERF_SALMA
	const EVENT_BEAT_COOLTRAINERF_LOLA
	const EVENT_BEAT_COOLTRAINERF_REENA
	const EVENT_BEAT_COOLTRAINERF_JENN
	const EVENT_BEAT_COOLTRAINERF_CARA
	const EVENT_BEAT_COOLTRAINERF_QUINN
	const EVENT_BEAT_COOLTRAINERF_LAYLA
	const EVENT_BEAT_COOLTRAINERF_IRIS
	const EVENT_BEAT_COOLTRAINERF_LILY
	const EVENT_BEAT_COOLTRAINERF_RIVER
; Beauty
	const EVENT_BEAT_BEAUTY_VICTORIA
	const EVENT_BEAT_BEAUTY_STEPH
	const EVENT_BEAT_BEAUTY_JULIA
	const EVENT_BEAT_BEAUTY_VALERIE
	const EVENT_BEAT_BEAUTY_OLIVIA
	const EVENT_BEAT_BEAUTY_ADELINE
	const EVENT_BEAT_BEAUTY_CAROL
	const EVENT_BEAT_BEAUTY_EMMA
	const EVENT_BEAT_BEAUTY_CYBIL
	const EVENT_BEAT_BEAUTY_SAMANTHA
; Pokemaniac
	const EVENT_BEAT_POKEMANIAC_BRENT
	const EVENT_BEAT_POKEMANIAC_LARRY
	const EVENT_BEAT_POKEMANIAC_ANDREW
	const EVENT_BEAT_POKEMANIAC_CALVIN
	const EVENT_BEAT_POKEMANIAC_SHANE
	const EVENT_BEAT_POKEMANIAC_BEN
	const EVENT_BEAT_POKEMANIAC_RON
	const EVENT_BEAT_POKEMANIAC_ETHAN
	const EVENT_BEAT_POKEMANIAC_DONALD
	const EVENT_BEAT_POKEMANIAC_HORTON
	const EVENT_BEAT_POKEMANIAC_ZACH
	const EVENT_BEAT_POKEMANIAC_MILLER
	const EVENT_BEAT_POKEMANIAC_ROLAND
	const EVENT_BEAT_POKEMANIAC_MAX
	const EVENT_BEAT_POKEMANIAC_JULIUS
	const EVENT_BEAT_POKEMANIAC_MICAH
	const EVENT_BEAT_POKEMANIAC_CARSON
	const EVENT_BEAT_POKEMANIAC_JUDE
; Gentleman
	const EVENT_BEAT_GENTLEMAN_PRESTON
	const EVENT_BEAT_GENTLEMAN_EDWARD
	const EVENT_BEAT_GENTLEMAN_GREGORY
	const EVENT_BEAT_GENTLEMAN_WESLEY
	const EVENT_BEAT_GENTLEMAN_MILTON
	const EVENT_BEAT_GENTLEMAN_BLAKE
	const EVENT_BEAT_GENTLEMAN_ALFRED
	const EVENT_BEAT_GENTLEMAN_RICHARD
	const EVENT_BEAT_GENTLEMAN_VICTOR
; Skier
	const EVENT_BEAT_SKIER_ROXANNE
	const EVENT_BEAT_SKIER_CLARISSA
; BugCatcher
	const EVENT_BEAT_BUG_CATCHER_BENNY
	const EVENT_BEAT_BUG_CATCHER_ED
	const EVENT_BEAT_BUG_CATCHER_ROB
	const EVENT_BEAT_BUG_CATCHER_AL
	const EVENT_BEAT_BUG_CATCHER_JOSH
	const EVENT_BEAT_BUG_CATCHER_DION
	const EVENT_BEAT_BUG_CATCHER_DANE
	const EVENT_BEAT_BUG_CATCHER_KEN
	const EVENT_BEAT_BUG_CATCHER_WAYNE
	const EVENT_BEAT_BUG_CATCHER_ABNER
	const EVENT_BEAT_BUG_CATCHER_ELLIS
	const EVENT_BEAT_BUG_CATCHER_DOUG
	const EVENT_BEAT_BUG_CATCHER_DON
	const EVENT_BEAT_BUG_CATCHER_DARIN
	const EVENT_BEAT_BUG_CATCHER_ARNIE
	const EVENT_BEAT_BUG_CATCHER_WADE
	const EVENT_BEAT_BUG_CATCHER_DYLAN
	const EVENT_BEAT_BUG_CATCHER_FINLEY
	const EVENT_BEAT_BUG_CATCHER_JON
	const EVENT_BEAT_BUG_CATCHER_ABEL
; Fisher
	const EVENT_BEAT_FISHER_JUSTIN
	const EVENT_BEAT_FISHER_ARNOLD
	const EVENT_BEAT_FISHER_SCOTT
	const EVENT_BEAT_FISHER_HENRY
	const EVENT_BEAT_FISHER_MARVIN
	const EVENT_BEAT_FISHER_TULLY
	const EVENT_BEAT_FISHER_RAYMOND
	const EVENT_BEAT_FISHER_JONAH
	const EVENT_BEAT_FISHER_KYLE
	const EVENT_BEAT_FISHER_MARTIN
	const EVENT_BEAT_FISHER_STEPHEN
	const EVENT_BEAT_FISHER_LUCA
	const EVENT_BEAT_FISHER_NELSON
	const EVENT_BEAT_FISHER_BARNEY
	const EVENT_BEAT_FISHER_WILTON
	const EVENT_BEAT_FISHER_FRED
	const EVENT_BEAT_FISHER_EMIL
	const EVENT_BEAT_FISHER_MARCO
	const EVENT_BEAT_FISHER_ARCHIE
	const EVENT_BEAT_FISHER_ROYCE
	const EVENT_BEAT_FISHER_RALPH
; SwimmerM
	const EVENT_BEAT_SWIMMERM_HAROLD
	const EVENT_BEAT_SWIMMERM_SIMON
	const EVENT_BEAT_SWIMMERM_RANDALL
	const EVENT_BEAT_SWIMMERM_CHARLIE
	const EVENT_BEAT_SWIMMERM_GEORGE
	const EVENT_BEAT_SWIMMERM_BERKE
	const EVENT_BEAT_SWIMMERM_KIRK
	const EVENT_BEAT_SWIMMERM_MATTHEW
	const EVENT_BEAT_SWIMMERM_JEROME
	const EVENT_BEAT_SWIMMERM_TUCKER
	const EVENT_BEAT_SWIMMERM_CAMERON
	const EVENT_BEAT_SWIMMERM_SETH
	const EVENT_BEAT_SWIMMERM_LEWIS
	const EVENT_BEAT_SWIMMERM_HAL
	const EVENT_BEAT_SWIMMERM_PATON
	const EVENT_BEAT_SWIMMERM_BRANDON
	const EVENT_BEAT_SWIMMERM_DARYL
	const EVENT_BEAT_SWIMMERM_TONY
	const EVENT_BEAT_SWIMMERM_CODY
	const EVENT_BEAT_SWIMMERM_WES
	const EVENT_BEAT_SWIMMERM_CARLOS
	const EVENT_BEAT_SWIMMERM_MACK
; SwimmerF
	const EVENT_BEAT_SWIMMERF_ELAINE
	const EVENT_BEAT_SWIMMERF_PAULA
	const EVENT_BEAT_SWIMMERF_KAYLEE
	const EVENT_BEAT_SWIMMERF_SUSIE
	const EVENT_BEAT_SWIMMERF_DENISE
	const EVENT_BEAT_SWIMMERF_KARA
	const EVENT_BEAT_SWIMMERF_WENDY
	const EVENT_BEAT_SWIMMERF_HEIDI
	const EVENT_BEAT_SWIMMERF_GINGER
	const EVENT_BEAT_SWIMMERF_NIKKI
	const EVENT_BEAT_SWIMMERF_DIANA
	const EVENT_BEAT_SWIMMERF_BRIANA
	const EVENT_BEAT_SWIMMERF_ELOISE
	const EVENT_BEAT_SWIMMERF_HANNAH
	const EVENT_BEAT_SWIMMERF_KYRIE
; Sailor
	const EVENT_BEAT_SAILOR_EUGENE
	const EVENT_BEAT_SAILOR_HARRY
	const EVENT_BEAT_SAILOR_TERRELL
	const EVENT_BEAT_SAILOR_KENT
	const EVENT_BEAT_SAILOR_ERNEST
	const EVENT_BEAT_SAILOR_JEFF
	const EVENT_BEAT_SAILOR_GARRETT
	const EVENT_BEAT_SAILOR_KENNETH
	const EVENT_BEAT_SAILOR_JARED
	const EVENT_BEAT_SAILOR_STANLEY
	const EVENT_BEAT_SAILOR_HUEY
	const EVENT_BEAT_SAILOR_PEDRO
	const EVENT_BEAT_SAILOR_ENZO
	const EVENT_BEAT_SAILOR_LOUIS
; SuperNerd
	const EVENT_BEAT_SUPER_NERD_ERIC
	const EVENT_BEAT_SUPER_NERD_SAM
	const EVENT_BEAT_SUPER_NERD_TOM
	const EVENT_BEAT_SUPER_NERD_PAT
	const EVENT_BEAT_SUPER_NERD_SHAWN
	const EVENT_BEAT_SUPER_NERD_TERU
	const EVENT_BEAT_SUPER_NERD_HUGH
	const EVENT_BEAT_SUPER_NERD_MARKUS
	const EVENT_BEAT_SUPER_NERD_CARY
	const EVENT_BEAT_SUPER_NERD_EMMETT
	const EVENT_BEAT_SUPER_NERD_WALDO
	const EVENT_BEAT_SUPER_NERD_JAMES
	const EVENT_BEAT_SUPER_NERD_MERLE
; Guitarist
	const EVENT_BEAT_GUITARIST_WYATT
	const EVENT_BEAT_GUITARIST_LOGAN
	const EVENT_BEAT_GUITARIST_CLYDE
	const EVENT_BEAT_GUITARIST_VINCENT
	const EVENT_BEAT_GUITARIST_EDGAR
; Hiker
	const EVENT_BEAT_HIKER_DANIEL
	const EVENT_BEAT_HIKER_RUSSELL
	const EVENT_BEAT_HIKER_PHILLIP
	const EVENT_BEAT_HIKER_LEONARD
	const EVENT_BEAT_HIKER_BENJAMIN
	const EVENT_BEAT_HIKER_ERIK
	const EVENT_BEAT_HIKER_MICHAEL
	const EVENT_BEAT_HIKER_KENNY
	const EVENT_BEAT_HIKER_TIMOTHY
	const EVENT_BEAT_HIKER_BAILEY
	const EVENT_BEAT_HIKER_TIM
	const EVENT_BEAT_HIKER_NOLAND
	const EVENT_BEAT_HIKER_SIDNEY
	const EVENT_BEAT_HIKER_WALTER
	const EVENT_BEAT_HIKER_JIM
	const EVENT_BEAT_HIKER_ANTHONY
	const EVENT_BEAT_HIKER_QUENTIN
	const EVENT_BEAT_HIKER_PARRY
	const EVENT_BEAT_HIKER_PATRICK
	const EVENT_BEAT_HIKER_ALEC
	const EVENT_BEAT_HIKER_DIEGO
	const EVENT_BEAT_HIKER_LEONEL
; Biker
	const EVENT_BEAT_BIKER_DWAYNE
	const EVENT_BEAT_BIKER_HARRIS
	const EVENT_BEAT_BIKER_ZEKE
	const EVENT_BEAT_BIKER_CHARLES
	const EVENT_BEAT_BIKER_REESE
	const EVENT_BEAT_BIKER_JOEL
	const EVENT_BEAT_BIKER_GLENN
	const EVENT_BEAT_BIKER_JOSEPH
	const EVENT_BEAT_BIKER_AIDEN
	const EVENT_BEAT_BIKER_TEDDY
	const EVENT_BEAT_BIKER_MARKEY
	const EVENT_BEAT_BIKER_RILEY
	const EVENT_BEAT_BIKER_THERON
	const EVENT_BEAT_BIKER_EOIN
	const EVENT_BEAT_BIKER_NOLAN
; Burglar
	const EVENT_BEAT_BURGLAR_DUNCAN
	const EVENT_BEAT_BURGLAR_EDDIE
	const EVENT_BEAT_BURGLAR_COREY
	const EVENT_BEAT_BURGLAR_BARRY
	const EVENT_BEAT_BURGLAR_JERRY
; Firebreather
	const EVENT_BEAT_FIREBREATHER_RAY
	const EVENT_BEAT_FIREBREATHER_BILL
	const EVENT_BEAT_FIREBREATHER_EVAN
	const EVENT_BEAT_FIREBREATHER_WALT
	const EVENT_BEAT_FIREBREATHER_LEO
	const EVENT_BEAT_FIREBREATHER_ALEX
; Juggler
	const EVENT_BEAT_JUGGLER_FRITZ
	const EVENT_BEAT_JUGGLER_OTIS
	const EVENT_BEAT_JUGGLER_BURT
	const EVENT_BEAT_JUGGLER_FINNLEY
	const EVENT_BEAT_JUGGLER_DUSTIN
	const EVENT_BEAT_JUGGLER_LYLE
	const EVENT_BEAT_JUGGLER_DARIUS
	const EVENT_BEAT_JUGGLER_JULIEN
	const EVENT_BEAT_JUGGLER_MAXIMO
	const EVENT_BEAT_JUGGLER_DARIO
	const EVENT_BEAT_JUGGLER_GILBERT
	const EVENT_BEAT_JUGGLER_IRWIN
	const EVENT_BEAT_JUGGLER_RODNEY
; Blackbelt
	const EVENT_BEAT_BLACKBELT_TAKESHI
	const EVENT_BEAT_BLACKBELT_BRUCE
	const EVENT_BEAT_BLACKBELT_JACKIE
	const EVENT_BEAT_BLACKBELT_JET
	const EVENT_BEAT_BLACKBELT_MASTER
	const EVENT_BEAT_BLACKBELT_WAI
	const EVENT_BEAT_BLACKBELT_TY
	const EVENT_BEAT_BLACKBELT_CHO
	const EVENT_BEAT_BLACKBELT_YOSHI
	const EVENT_BEAT_BLACKBELT_KENJI
	const EVENT_BEAT_BLACKBELT_LEE
	const EVENT_BEAT_BLACKBELT_LAO
	const EVENT_BEAT_BLACKBELT_KIYO
; Psychic
	const EVENT_BEAT_PSYCHIC_NATHAN
	const EVENT_BEAT_PSYCHIC_FRANKLIN
	const EVENT_BEAT_PSYCHIC_HERMAN
	const EVENT_BEAT_PSYCHIC_GREG
	const EVENT_BEAT_PSYCHIC_NORMAN
	const EVENT_BEAT_PSYCHIC_MARK
	const EVENT_BEAT_PSYCHIC_PHIL
	const EVENT_BEAT_PSYCHIC_IDRIS
	const EVENT_BEAT_PSYCHIC_KENAN
	const EVENT_BEAT_PSYCHIC_CALEB
; Picknicker
	const EVENT_BEAT_PICNICKER_SOPHIA
	const EVENT_BEAT_PICNICKER_EMILY
	const EVENT_BEAT_PICNICKER_ELLIE
	const EVENT_BEAT_PICNICKER_GINA
	const EVENT_BEAT_PICNICKER_AZRIEL
	const EVENT_BEAT_PICNICKER_ERIN
	const EVENT_BEAT_PICNICKER_EDNA
	const EVENT_BEAT_PICNICKER_BROOKE
	const EVENT_BEAT_PICNICKER_KIM
	const EVENT_BEAT_PICNICKER_CINDY
	const EVENT_BEAT_PICNICKER_HOPE
	const EVENT_BEAT_PICNICKER_SHARON
	const EVENT_BEAT_PICNICKER_DEBRA
	const EVENT_BEAT_PICNICKER_TANYA
	const EVENT_BEAT_PICNICKER_SELINA
	const EVENT_BEAT_PICNICKER_PIPER
	const EVENT_BEAT_PICNICKER_MARIA
	const EVENT_BEAT_PICNICKER_TIFFANY
	const EVENT_BEAT_PICNICKER_CARRIE
	const EVENT_BEAT_PICNICKER_LUCY
	const EVENT_BEAT_PICNICKER_DAWN
	const EVENT_BEAT_PICNICKER_NICOLE
	const EVENT_BEAT_PICNICKER_MEGAN
	const EVENT_BEAT_PICNICKER_ROBIN
	const EVENT_BEAT_PICNICKER_LIZ
; Camper
	const EVENT_BEAT_CAMPER_ISAAC
	const EVENT_BEAT_CAMPER_IVAN
	const EVENT_BEAT_CAMPER_TANNER
	const EVENT_BEAT_CAMPER_ELLIOT
	const EVENT_BEAT_CAMPER_LLOYD
	const EVENT_BEAT_CAMPER_DEAN
	const EVENT_BEAT_CAMPER_SID
	const EVENT_BEAT_CAMPER_TED
	const EVENT_BEAT_CAMPER_GRANT
	const EVENT_BEAT_CAMPER_CLARK
	const EVENT_BEAT_CAMPER_TODD
	const EVENT_BEAT_CAMPER_SPENCER
	const EVENT_BEAT_CAMPER_DILAN
	const EVENT_BEAT_CAMPER_TERRY
; Sage
	const EVENT_BEAT_SAGE_EZRA
	const EVENT_BEAT_SAGE_KYLO
	const EVENT_BEAT_SAGE_KODA
	const EVENT_BEAT_SAGE_MUSA
	const EVENT_BEAT_SAGE_BO
	const EVENT_BEAT_SAGE_PING
	const EVENT_BEAT_SAGE_CHOW
	const EVENT_BEAT_SAGE_NICO
	const EVENT_BEAT_SAGE_NOE
	const EVENT_BEAT_SAGE_JIN
	const EVENT_BEAT_SAGE_KYRO
	const EVENT_BEAT_SAGE_LI
	const EVENT_BEAT_SAGE_GAKU
	const EVENT_BEAT_SAGE_MASA
	const EVENT_BEAT_SAGE_KOJI
; Medium
	const EVENT_BEAT_MEDIUM_MARTHA
	const EVENT_BEAT_MEDIUM_GRACE
	const EVENT_BEAT_MEDIUM_BETHANY
	const EVENT_BEAT_MEDIUM_MARGRET
	const EVENT_BEAT_MEDIUM_ETHEL
	const EVENT_BEAT_MEDIUM_REBECCA
	const EVENT_BEAT_MEDIUM_DORIS
	const EVENT_BEAT_MEDIUM_JADE
	const EVENT_BEAT_MEDIUM_LYDIA
	const EVENT_BEAT_MEDIUM_DELILAH
	const EVENT_BEAT_MEDIUM_MAYA
	const EVENT_BEAT_MEDIUM_WILLOW
	const EVENT_BEAT_MEDIUM_ABIGAIL
	const EVENT_BEAT_MEDIUM_HAZEL
	const EVENT_BEAT_MEDIUM_NAOMI
	const EVENT_BEAT_MEDIUM_STELLA
	const EVENT_BEAT_MEDIUM_CHEL
	const EVENT_BEAT_MEDIUM_MINA
	const EVENT_BEAT_MEDIUM_LEONA
; Boarder
	const EVENT_BEAT_BOARDER_RONALD
	const EVENT_BEAT_BOARDER_SHAUN
; PokefanM
	const EVENT_BEAT_POKEFANM_TREVOR
	const EVENT_BEAT_POKEFANM_WILLIAM
	const EVENT_BEAT_POKEFANM_ROBERT
	const EVENT_BEAT_POKEFANM_JOSHUA
	const EVENT_BEAT_POKEFANM_AUSTIN
	const EVENT_BEAT_POKEFANM_DEREK
	const EVENT_BEAT_POKEFANM_COLIN
	const EVENT_BEAT_POKEFANM_BRENDAN
; PokefanF
	const EVENT_BEAT_POKEFANF_BEVERLY
	const EVENT_BEAT_POKEFANF_GEORGIA
	const EVENT_BEAT_POKEFANF_AUDREY
	const EVENT_BEAT_POKEFANF_ELEANOR
	const EVENT_BEAT_POKEFANF_RUTH
; KimonoGirl
	const EVENT_BEAT_KIMONO_GIRL_NAOKO
	const EVENT_BEAT_KIMONO_GIRL_SAYO
	const EVENT_BEAT_KIMONO_GIRL_ZUKI
	const EVENT_BEAT_KIMONO_GIRL_KUNI
	const EVENT_BEAT_KIMONO_GIRL_MIKI
	const EVENT_BEAT_KIMONO_GIRL_AOKI
	const EVENT_BEAT_KIMONO_GIRL_YUKI
; Twins
	const EVENT_BEAT_TWINS_KAYANDTIA
	const EVENT_BEAT_TWINS_ANNANDANNE
	const EVENT_BEAT_TWINS_AMYANDMAY
	const EVENT_BEAT_TWINS_MEGANDPEG
	const EVENT_BEAT_TWINS_JOANDZOE
; Officer
	const EVENT_BEAT_OFFICER_REX
	const EVENT_BEAT_OFFICER_CARTER
	const EVENT_BEAT_OFFICER_KEITH
	const EVENT_BEAT_OFFICER_DIRK
; Ninja ; Esuine
;	const EVENT_BEAT_MYSTICALMAN_ESUINE
	const EVENT_BEAT_NINJA_KOA
	const EVENT_BEAT_NINJA_KHAI
	const EVENT_BEAT_NINJA_JONIN
	const EVENT_BEAT_NINJA_CHUNIN
	const EVENT_BEAT_NINJA_GENIN
	const EVENT_BEAT_NINJA_TEISATSU
	const EVENT_BEAT_NINJA_KANCHO
	const EVENT_BEAT_NINJA_KISHU
	const EVENT_BEAT_NINJA_KONRAN
	const EVENT_BEAT_NINJA_SEKKO
;	const EVENT_BEAT_NINJA_IROH
;	const EVENT_BEAT_NINJA_AANG
;	const EVENT_BEAT_NINJA_ZUKO
; Couple
	const EVENT_BEAT_COUPLE_TIMANDSUE
	const EVENT_BEAT_COUPLE_DUFFANDEDA
	const EVENT_BEAT_COUPLE_MOEANDLULU
	const EVENT_BEAT_COUPLE_VICANDTARA
; CoolDuo
	const EVENT_BEAT_COOL_DUO_ZACANDJEN
	const EVENT_BEAT_COOL_DUO_THOMANDKAE
	const EVENT_BEAT_COOL_DUO_ELANANDIDA
; used 535
; running total used 1535

	const_next 1600
; Phone events
	const EVENT_JACK_ASKED_FOR_PHONE_NUMBER
	const EVENT_IAN_ASKED_FOR_PHONE_NUMBER
	const EVENT_BEVERLY_ASKED_FOR_PHONE_NUMBER
	const EVENT_WALT_ASKED_FOR_PHONE_NUMBER        ;used
	const EVENT_HUEY_ASKED_FOR_PHONE_NUMBER
	const EVENT_KRISE_ASKED_FOR_PHONE_NUMBER
	const EVENT_GAVIN_ASKED_FOR_PHONE_NUMBER
	const EVENT_ALFRED_ASKED_FOR_PHONE_NUMBER
	const EVENT_BETH_ASKED_FOR_PHONE_NUMBER
	const EVENT_DOUG_ASKED_FOR_PHONE_NUMBER
	const EVENT_JOSE_ASKED_FOR_PHONE_NUMBER
	const EVENT_ROB_ASKED_FOR_PHONE_NUMBER
	const EVENT_REENA_ASKED_FOR_PHONE_NUMBER
	const EVENT_KYLE_ASKED_FOR_PHONE_NUMBER
	const EVENT_JOEY_ASKED_FOR_PHONE_NUMBER
	const EVENT_TANNER_ASKED_FOR_PHONE_NUMBER
	const EVENT_WADE_ASKED_FOR_PHONE_NUMBER
	const EVENT_KENNY_ASKED_FOR_PHONE_NUMBER
	const EVENT_RALPH_ASKED_FOR_PHONE_NUMBER
	const EVENT_TIM_AND_SUE_ASKED_FOR_PHONE_NUMBER
	const EVENT_LIZ_ASKED_FOR_PHONE_NUMBER
	const EVENT_JAMIE_ASKED_FOR_PHONE_NUMBER
	const EVENT_ANTHONY_ASKED_FOR_PHONE_NUMBER
	const EVENT_TORIN_ASKED_FOR_PHONE_NUMBER
	const EVENT_TODD_ASKED_FOR_PHONE_NUMBER
	const EVENT_BILLY_ASKED_FOR_PHONE_NUMBER
	const EVENT_GINA_ASKED_FOR_PHONE_NUMBER
	const EVENT_HILLARY_ASKED_FOR_PHONE_NUMBER
	const EVENT_IRWIN_ASKED_FOR_PHONE_NUMBER       ;used
	const EVENT_KAY_AND_TIA_ASKED_FOR_PHONE_NUMBER
	const EVENT_ARNIE_ASKED_FOR_PHONE_NUMBER
	const EVENT_AIDEN_ASKED_FOR_PHONE_NUMBER
	const EVENT_ALAN_ASKED_FOR_PHONE_NUMBER
	const EVENT_EOIN_ASKED_FOR_PHONE_NUMBER
	const EVENT_REESE_ASKED_FOR_PHONE_NUMBER
	const EVENT_DANA_ASKED_FOR_PHONE_NUMBER
	const EVENT_CHAD_ASKED_FOR_PHONE_NUMBER
	const EVENT_DEREK_ASKED_FOR_PHONE_NUMBER
	const EVENT_TULLY_ASKED_FOR_PHONE_NUMBER
	const EVENT_BRENT_ASKED_FOR_PHONE_NUMBER
	const EVENT_TIFFANY_ASKED_FOR_PHONE_NUMBER
	const EVENT_VANCE_ASKED_FOR_PHONE_NUMBER
	const EVENT_WILTON_ASKED_FOR_PHONE_NUMBER
	const EVENT_KENJI_ASKED_FOR_PHONE_NUMBER
	const EVENT_PARRY_ASKED_FOR_PHONE_NUMBER
	const EVENT_ERIN_ASKED_FOR_PHONE_NUMBER
	const EVENT_BUENA_OFFERED_HER_PHONE_NUMBER
	const EVENT_BUENA_OFFERED_HER_PHONE_NUMBER_NO_BLUE_CARD
	const EVENT_KENJI_ON_BREAK
	const_skip
; used 50
	const EVENT_YOUNGSTER_IAN_HAS_GIFT ;EVENT_GOT_BERRY_FROM_YOUNGSTER_IAN

	const EVENT_TULLY_GAVE_WATER_STONE
	const EVENT_ALAN_GAVE_FIRE_STONE
	const EVENT_DANA_GAVE_THUNDERSTONE
	const EVENT_GINA_GAVE_LEAF_STONE
	const EVENT_JAMIE_GAVE_MOON_STONE
	const EVENT_TANNER_GAVE_SUN_STONE
	const EVENT_TIFFANY_GAVE_DUSK_STONE

	const EVENT_ERIN_HAS_CALCIUM
	const EVENT_GOT_CALCIUM_FROM_ERIN
	const EVENT_VANCE_HAS_CARBOS
	const EVENT_GOT_CARBOS_FROM_VANCE



	const EVENT_WILTON_HAS_ULTRA_BALL
	const EVENT_WILTON_HAS_GREAT_BALL
	const EVENT_WILTON_HAS_POKE_BALL

	const EVENT_HUEY_PROTEIN
	const EVENT_GOT_PROTEIN_FROM_HUEY
	const EVENT_JOEY_HP_UP
	const EVENT_GOT_HP_UP_FROM_JOEY
	const EVENT_PARRY_IRON
	const EVENT_GOT_IRON_FROM_PARRY

; used 67
; group total used 67
; running total used 1667

	const_next 1700
; Berries and Apricorns
	const EVENT_ROUTE_1_ORAN_BERRY
	const EVENT_ROUTE_1_BLK_APRICORN
	const EVENT_VIRIDIAN_FOREST_ORAN_BERRY
	const EVENT_VIRIDIAN_FOREST_PECHA_BERRY
	const EVENT_ROUTE_2N_PNK_APRICORN
	const EVENT_PEWTER_CITY_CHESTO_BERRY
	const EVENT_PEWTER_CITY_PERSIM_BERRY
	const EVENT_PEWTER_CITY_BLU_APRICORN
	const EVENT_PEWTER_CITY_WHT_APRICORN
	const EVENT_ROUTE_24_LEPPA_BERRY
	const EVENT_BILLS_BACK_YARD_LUM_BERRY
	const EVENT_ROUTE_8_RAWST_BERRY
	const EVENT_ROUTE_8_YLW_APRICORN
	const EVENT_ROUTE_11_CHERI_BERRY
	const EVENT_ROUTE_11_GRN_APRICORN
	const EVENT_ROUTE_16_SITRUS_BERRY
	const EVENT_FUCHSIA_CITY_ASPEAR_BERRY
	const EVENT_FUCHSIA_CITY_RED_APRICORN
	const EVENT_ROUTE_26_LEPPA_BERRY
	const EVENT_ROUTE_26_SITRUS_BERRY
	const EVENT_ROUTE_39_ORAN_BERRY
	const EVENT_ROUTE_38_CHESTO_BERRY
	const EVENT_ROUTE_38_WHT_APRICORN
	const EVENT_ROUTE_37_RED_APRICORN
	const EVENT_ROUTE_37_BLU_APRICORN
	const EVENT_ROUTE_37_BLK_APRICORN
	const EVENT_ROUTE_36_RAWST_BERRY
	const EVENT_ROUTE_35_LEPPA_BERRY
	const EVENT_ROUTE_35_GRN_APRICORN
	const EVENT_AZALEA_TOWN_WHT_APRICORN
	const EVENT_ROUTE_33_BLK_APRICORN
	const EVENT_VIOLET_CITY_YLW_APRICORN
	const EVENT_ROUTE_30_ORAN_BERRY
	const EVENT_ROUTE_30_PECHA_BERRY
	const EVENT_ROUTE_30_PNK_APRICORN
	const EVENT_ROUTE_29_ORAN_BERRY
	const EVENT_ROUTE_42_PNK_APRICORN
	const EVENT_ROUTE_42_GRN_APRICORN
	const EVENT_ROUTE_42_YLW_APRICORN
	const EVENT_ROUTE_43_PERSIM_BERRY
	const EVENT_ROUTE_43_BLU_APRICORN
	const EVENT_ROUTE_44_ASPEAR_BERRY
	const EVENT_ROUTE_44_RED_APRICORN
	const EVENT_ROUTE_45_LEPPA_BERRY
	const EVENT_ROUTE_45_LUM_BERRY
	const EVENT_ROUTE_46_CHERI_BERRY
	const EVENT_ROUTE_46_SITRUS_BERRY
; Sour Crystal old berry flags
;	const EVENT_ROUTE_29_BERRY
;	const EVENT_ROUTE_29_APRICORN
;	const EVENT_ROUTE_30_BERRY
;	const EVENT_ROUTE_30_BERRY_2
;	const EVENT_ROUTE_30_APRICORN
;	const EVENT_ROUTE_30_APRICORN_2
;	const EVENT_ROUTE_31_BERRY
;	const EVENT_ROUTE_31_APRICORN
;	const EVENT_VIOLET_BERRY
;	const EVENT_VIOLET_APRICORN
;	const EVENT_ROUTE_33_BERRY
;	const EVENT_ROUTE_33_APRICORN
;	const EVENT_ROUTE_33_APRICORN_2
;	const EVENT_AZALEA_APRICORN
;	const EVENT_ROUTE_35_BERRY
;	const EVENT_ROUTE_35_APRICORN
;	const EVENT_ROUTE_36_BERRY
;	const EVENT_ROUTE_36_APRICORN
;	const EVENT_ROUTE_37_APRICORN
;	const EVENT_ROUTE_37_APRICORN_2
;	const EVENT_ROUTE_37_APRICORN_3
;	const EVENT_ROUTE_38_BERRY
;	const EVENT_ROUTE_38_APRICORN
;	const EVENT_ROUTE_39_BERRY
;	const EVENT_ROUTE_39_APRICORN
;	const EVENT_ROUTE_42_APRICORN
;	const EVENT_ROUTE_42_APRICORN_2
;	const EVENT_ROUTE_42_APRICORN_3
;	const EVENT_ROUTE_43_BERRY
;	const EVENT_ROUTE_43_APRICORN
;	const EVENT_ROUTE_44_BERRY
;	const EVENT_ROUTE_44_APRICORN
;	const EVENT_ROUTE_45_BERRY
;	const EVENT_ROUTE_45_APRICORN
;	const EVENT_ROUTE_46_BERRY
;	const EVENT_ROUTE_46_BERRY_2
;	const EVENT_ROUTE_46_APRICORN
;	const EVENT_ROUTE_46_APRICORN_2
;	const EVENT_ROUTE_26_BERRY
;	const EVENT_ROUTE_26_APRICORN
;	const EVENT_ROUTE_1_BERRY
;	const EVENT_ROUTE_1_APRICORN
;	const EVENT_VIRIDIAN_FOREST_BERRY
;	const EVENT_VIRIDIAN_FOREST_APRICORN
;	const EVENT_PEWTER_BERRY
;	const EVENT_PEWTER_BERRY_2
;	const EVENT_PEWTER_APRICORN
;	const EVENT_PEWTER_APRICORN_2
;	const EVENT_ROUTE_8_BERRY
;	const EVENT_ROUTE_8_APRICORN
;	const EVENT_ROUTE_11_BERRY
;	const EVENT_ROUTE_11_APRICORN
;	const EVENT_FUCHSIA_BERRY
;	const EVENT_FUCHSIA_APRICORN
; used 47
; group total used 47
; running total used 1747

	const_next 1800
; Kurt Apricorn events
	const EVENT_GAVE_KURT_SON_RED_APRICORN
	const EVENT_GAVE_KURT_SON_BLU_APRICORN
	const EVENT_GAVE_KURT_SON_YLW_APRICORN
	const EVENT_GAVE_KURT_SON_GRN_APRICORN
	const EVENT_GAVE_KURT_SON_WHT_APRICORN
	const EVENT_GAVE_KURT_SON_BLK_APRICORN
	const EVENT_GAVE_KURT_SON_PNK_APRICORN
	const EVENT_GAVE_KURT_RED_APRICORN
	const EVENT_GAVE_KURT_BLU_APRICORN
	const EVENT_GAVE_KURT_YLW_APRICORN
	const EVENT_GAVE_KURT_GRN_APRICORN
	const EVENT_GAVE_KURT_WHT_APRICORN
	const EVENT_GAVE_KURT_BLK_APRICORN
	const EVENT_GAVE_KURT_PNK_APRICORN
	const_skip
; used 15
;
; Decorations
	const EVENT_DECO_BED_1
	const EVENT_DECO_BED_2
	const EVENT_DECO_BED_3
	const EVENT_DECO_BED_4
	const EVENT_DECO_CARPET_1
	const EVENT_DECO_CARPET_2
	const EVENT_DECO_CARPET_3
	const EVENT_DECO_CARPET_4
	const EVENT_DECO_PLANT_1
	const EVENT_DECO_PLANT_2
	const EVENT_DECO_PLANT_3
	const EVENT_DECO_POSTER_1
	const EVENT_DECO_POSTER_2
	const EVENT_DECO_POSTER_3
	const EVENT_DECO_POSTER_4
	const EVENT_DECO_FAMICOM
	const EVENT_DECO_SNES
	const EVENT_DECO_N64
	const EVENT_DECO_VIRTUAL_BOY
	const EVENT_DECO_PIKACHU_DOLL
	const EVENT_DECO_SURFING_PIKACHU_DOLL
	const EVENT_DECO_CLEFAIRY_DOLL
	const EVENT_DECO_JIGGLYPUFF_DOLL
	const EVENT_DECO_BULBASAUR_DOLL
	const EVENT_DECO_CHARMANDER_DOLL
	const EVENT_DECO_SQUIRTLE_DOLL
	const EVENT_DECO_POLIWAG_DOLL
	const EVENT_DECO_DIGLETT_DOLL
	const EVENT_DECO_STARYU_DOLL
	const EVENT_DECO_MAGIKARP_DOLL
	const EVENT_DECO_ODDISH_DOLL
	const EVENT_DECO_GENGAR_DOLL
	const EVENT_DECO_SHELLDER_DOLL
	const EVENT_DECO_GRIMER_DOLL
	const EVENT_DECO_VOLTORB_DOLL
	const EVENT_DECO_WEEDLE_DOLL
	const EVENT_DECO_UNOWN_DOLL
	const EVENT_DECO_GEODUDE_DOLL
	const EVENT_DECO_MACHOP_DOLL
	const EVENT_DECO_TENTACOOL_DOLL
	const EVENT_PLAYERS_ROOM_POSTER
	const EVENT_DECO_GOLD_TROPHY
	const EVENT_DECO_SILVER_TROPHY
	const EVENT_DECO_BIG_SNORLAX_DOLL
	const EVENT_DECO_BIG_ONIX_DOLL
	const EVENT_DECO_BIG_LAPRAS_DOLL
; used 46
;
; Ruins of Alph puzzles
	const EVENT_MADE_UNOWN_APPEAR_IN_RUINS
	const EVENT_SOLVED_KABUTO_PUZZLE
	const EVENT_SOLVED_AERODACTYL_PUZZLE
	const EVENT_SOLVED_OMANYTE_PUZZLE
	const EVENT_SOLVED_HO_OH_PUZZLE
	const EVENT_WALL_OPENED_IN_KABUTO_CHAMBER
	const EVENT_WALL_OPENED_IN_AERODACTYL_CHAMBER
	const EVENT_WALL_OPENED_IN_OMANYTE_CHAMBER
	const EVENT_WALL_OPENED_IN_HO_OH_CHAMBER
; Ruins of Alph itemballs
	const EVENT_KABUTO_ITEM_ROOM_ORAN_BERRY
	const EVENT_KABUTO_ITEM_ROOM_PECHA_BERRY
	const EVENT_KABUTO_ITEM_ROOM_HEAL_POWDER
	const EVENT_KABUTO_ITEM_ROOM_ENERGYPOWDER
	const EVENT_AERODACTYL_ITEM_ROOM_SITRUS_BERRY
	const EVENT_AERODACTYL_ITEM_ROOM_MOON_STONE
	const EVENT_AERODACTYL_ITEM_ROOM_HEAL_POWDER
	const EVENT_AERODACTYL_ITEM_ROOM_ENERGY_ROOT
	const EVENT_OMANYTE_ITEM_ROOM_LEPPA_BERRY
	const EVENT_OMANYTE_ITEM_ROOM_MYSTIC_WATER
	const EVENT_OMANYTE_ITEM_ROOM_STARDUST
	const EVENT_OMANYTE_ITEM_ROOM_STAR_PIECE
	const EVENT_HO_OH_ITEM_ROOM_SITRUS_BERRY
	const EVENT_HO_OH_ITEM_ROOM_LEPPA_BERRY
	const EVENT_HO_OH_ITEM_ROOM_REVIVAL_HERB
	const EVENT_HO_OH_ITEM_ROOM_CHARCOAL
; used 25
; group total used 86
; running total used 1886

;	const_next 1900

	const_next 2048
DEF NUM_EVENTS EQU const_value ; 800

; Johto story events
;	const EVENT_HEALED_MOOMOO
;	const EVENT_TALKED_TO_FARMER_ABOUT_MOOMOO
;	const EVENT_GOT_SHUCKIE
;	const EVENT_MANIA_TOOK_SHUCKIE_OR_LET_YOU_KEEP_HIM
;	const EVENT_GOT_A_POKEMON_FROM_ELM
;	const EVENT_GOT_CYNDAQUIL_FROM_ELM
;	const EVENT_GOT_TOTODILE_FROM_ELM
;	const EVENT_GOT_CHIKORITA_FROM_ELM
;	const EVENT_GOT_MYSTERY_EGG_FROM_MR_POKEMON
;	const EVENT_GAVE_MYSTERY_EGG_TO_ELM
;	const EVENT_JASMINE_RETURNED_TO_GYM
;	const EVENT_CLEARED_ROCKET_HIDEOUT
;	const EVENT_GOT_SECRETPOTION_FROM_PHARMACY
;	const EVENT_REFUSED_TO_HELP_LANCE_AT_LAKE_OF_RAGE
;	const EVENT_GOT_ORAN_BERRY_FROM_ROUTE_30_HOUSE
;	const EVENT_HERDED_FARFETCHD
;	const EVENT_CLEARED_SLOWPOKE_WELL
;	const EVENT_REFUSED_TO_TAKE_EGG_FROM_ELMS_AIDE
;	const EVENT_GOT_TOGEPI_EGG_FROM_ELMS_AIDE
;	const EVENT_FAST_SHIP_LAZY_SAILOR
;	const EVENT_FAST_SHIP_INFORMED_ABOUT_LAZY_SAILOR
;	const EVENT_JASMINE_EXPLAINED_AMPHYS_SICKNESS
;	const EVENT_OLIVINE_LIGHTHOUSE_AMPHY_SICK
;	const EVENT_GOT_TM63_SNORE_FROM_MOOMOO_FARM
;	const EVENT_TALKED_TO_MOM_AFTER_MYSTERY_EGG_QUEST
;	const EVENT_DUDE_TALKED_TO_YOU ; shouldnt need this
;	const EVENT_ELM_CALLED_ABOUT_STOLEN_POKEMON
;	const EVENT_GOT_TM05_ROAR
;	const EVENT_GOT_TM50_NIGHTMARE
;	const EVENT_GOT_TM10_HIDDEN_POWER
;	const EVENT_GOT_TM36_SLUDGE_BOMB
;	const EVENT_GOT_TM02_HEADBUTT
;	const EVENT_GOT_TM47_STEEL_WING
;	const EVENT_GOT_TM37_SANDSTORM
;	const EVENT_GOT_TM12_SWEET_SCENT
;	const EVENT_RECEIVED_CARD_KEY
;	const EVENT_LANCE_HEALED_YOU_IN_TEAM_ROCKET_BASE
;	const EVENT_GOT_MYSTIC_WATER_IN_CHERRYGROVE
;	const EVENT_GOT_EEVEE
;	const EVENT_GOT_KENYA
;	const EVENT_GAVE_KENYA
;	const EVENT_GOT_HP_UP_FROM_RANDY
;	const EVENT_TOGEPI_HATCHED
;	const EVENT_SHOWED_TOGEPI_TO_ELM
;	const EVENT_GOT_EVERSTONE_FROM_ELM
;	const EVENT_GOT_MIRACLE_SEED_IN_ROUTE_32
;	const EVENT_GOT_CHARCOAL_IN_CHARCOAL_KILN
;	const EVENT_DECIDED_TO_HELP_LANCE
;	const EVENT_GOT_SOFT_SAND_FROM_KATE
;	const EVENT_TOLD_ELM_ABOUT_TOGEPI_OVER_THE_PHONE
;	const EVENT_LEARNED_HAIL_GIOVANNI
;	const EVENT_OPENED_DOOR_TO_ROCKET_HIDEOUT_TRANSMITTER
;	const EVENT_LEARNED_SLOWPOKETAIL
;	const EVENT_LEARNED_RATICATE_TAIL
;	const EVENT_OPENED_DOOR_TO_GIOVANNIS_OFFICE
;	const EVENT_WILLS_ROOM_ENTRANCE_CLOSED
;	const EVENT_WILLS_ROOM_EXIT_OPEN
;	const EVENT_KOGAS_ROOM_ENTRANCE_CLOSED
;	const EVENT_KOGAS_ROOM_EXIT_OPEN
;	const EVENT_BRUNOS_ROOM_ENTRANCE_CLOSED
;	const EVENT_BRUNOS_ROOM_EXIT_OPEN
;	const EVENT_KARENS_ROOM_ENTRANCE_CLOSED
;	const EVENT_KARENS_ROOM_EXIT_OPEN
;	const EVENT_LANCES_ROOM_ENTRANCE_CLOSED
;	const EVENT_LANCES_ROOM_EXIT_OPEN
;	const EVENT_BEAT_RIVAL_IN_MT_MOON
;
; New to Crystal
;	const EVENT_ECRUTEAK_GYM_GRAMPS
;	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_FISHER
;	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_YOUNGSTERS
;	const EVENT_DRAGON_SHRINE_CLAIR
;	const EVENT_PLAYERS_NEIGHBORS_HOUSE_NEIGHBOR
;	const EVENT_CIANWOOD_CITY_EUSINE
;	const EVENT_SAW_SUICUNE_AT_CIANWOOD_CITY
;	const EVENT_SAW_SUICUNE_ON_ROUTE_42
;	const EVENT_SAW_SUICUNE_ON_ROUTE_36
;	const EVENT_TIN_TOWER_1F_SUICUNE
;	const EVENT_TIN_TOWER_1F_ENTEI
;	const EVENT_TIN_TOWER_1F_RAIKOU
;	const EVENT_TIN_TOWER_1F_EUSINE
;	const EVENT_TIN_TOWER_1F_WISE_TRIO_1
;	const EVENT_TIN_TOWER_1F_WISE_TRIO_2
;	const EVENT_ECRUTEAK_TIN_TOWER_ENTRANCE_WANDERING_SAGE
;	const EVENT_ECRUTEAK_CITY_GRAMPS
;	const EVENT_BUGGING_KURT_TOO_MUCH
;	const EVENT_TALKED_TO_RUINS_COWARD
;	const EVENT_WELCOMED_TO_POKECOM_CENTER
;	const EVENT_FOUGHT_EUSINE