	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, WATER, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, WATER, WATER, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GRAY, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, WATER, WATER, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GRAY, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, WATER
